#!/bin/sh
# LoopTroop installer for macOS and Linux.
#
#   curl -fsSL https://www.looptroop.ovh/install | sh
#   curl -fsSL https://www.looptroop.ovh/install | sh -s -- --version 9.9.9
#   curl -fsSL https://www.looptroop.ovh/install | sh -s -- --binary
#
# Downloads what a LoopTroop release published, checks it against the checksum
# that release recorded, and installs it: the npm package with npm by default,
# or with `--binary` the standalone executable into ~/.looptroop. It never
# installs Node and never asks for sudo.
#
# All of the actual work is in `scripts/installer-core.mjs`, copied verbatim
# into the block at the bottom of this file. Node is required to install
# LoopTroop at all, so doing the JSON, HTTPS, semver and hashing there rather
# than here means one implementation instead of one per shell, and no dependency
# on curl, jq or shasum being present and identical on every platform.
set -eu

node_missing() {
# --- BEGIN node-floor (generated by scripts/sync-installers.mjs; do not edit) ---
  echo "LoopTroop needs Node.js 24.18.1 or newer and it is not on your PATH." >&2
  echo "" >&2
  case "$(uname -s 2>/dev/null || echo unknown)" in
    Darwin) echo "  brew install node" >&2 ;;
    Linux)  echo "  Use your distribution's package or https://github.com/nvm-sh/nvm" >&2 ;;
    *)      echo "  https://nodejs.org/" >&2 ;;
  esac
# --- END node-floor ---
  echo "  ...or download an installer from https://nodejs.org/" >&2
  echo "" >&2
  echo "Then run this installer again. It will not install Node for you." >&2
  # Including for `--binary`, which surprises people: the standalone executable
  # carries its own Node, but this installer is itself a Node program, so it
  # still needs one to run. Anybody with none at all wants the archive.
  for arg in "$@"; do
    if [ "$arg" = "--binary" ]; then
      echo "" >&2
      echo "That applies to --binary too: this installer is itself a Node program." >&2
      echo "With no Node at all, download and unpack the archive yourself:" >&2
      echo "  https://github.com/looptroop-ai/LoopTroop/releases/latest" >&2
      break
    fi
  done
  exit 1
}

command -v node >/dev/null 2>&1 || node_missing "$@"

work=$(mktemp -d 2>/dev/null || mktemp -d -t looptroop-install)
# `sh` has no scoped cleanup, and leaving the core behind in a world-readable
# temp directory is untidy rather than dangerous, but it is still litter.
#
# On EXIT, so that it also runs for a signal handled below: those handlers end
# in `exit`, and `exit` runs this. HUP is here because a terminal closing mid
# install is one of the ways this script stops.
trap 'rm -rf "$work"' EXIT INT TERM HUP
core="$work/installer-core.mjs"

# --- BEGIN installer-core (generated by scripts/sync-installers.mjs; do not edit) ---
cat > "$core" <<'LOOPTROOP_INSTALLER_CORE'
#!/usr/bin/env node
/**
 * Installs LoopTroop from a GitHub release, verifying the bytes first.
 *
 *   node installer-core.mjs [--version X.Y.Z] [--tarball PATH] [--dry-run]
 *   node installer-core.mjs --binary [--prefix DIR]
 *
 * This is the whole installer. `install.sh` and `install.ps1` are wrappers that
 * find Node, write this file to a temporary directory and run it — everything
 * that could get a decision wrong lives here, once, where it can be tested,
 * rather than twice in two shell dialects. `scripts/sync-installers.mjs`
 * copies this file into both wrappers and CI fails if a copy has drifted.
 *
 * Node is a hard prerequisite either way, so using it for JSON, semver, HTTPS
 * and hashing costs nothing and avoids depending on curl, jq, shasum or
 * certutil being present and behaving the same on three platforms.
 *
 * By default it installs an npm tarball, with npm (D2a): `npm uninstall -g
 * looptroop` and `npm install -g looptroop@latest` keep working afterwards,
 * which would not be true of an installer that unpacked files itself.
 *
 * `--binary` installs the standalone executable instead — one file carrying its
 * own Node — into a directory this installer owns. That mode unpacks files
 * itself, so it has to do by hand everything npm was doing for us: see
 * `installBinary` for why each step is there.
 *
 * Note that `--binary` still needs Node *to install*, because these wrappers are
 * Node programs. What it removes is Node as a requirement to **run** LoopTroop
 * afterwards. Somebody with no Node at all downloads the archive from the
 * releases page and unpacks it; there is nothing this script can do for them.
 */
import { spawnSync } from 'node:child_process'
import { createHash, randomUUID } from 'node:crypto'
import {
  chmodSync, closeSync, copyFileSync, existsSync, mkdirSync, mkdtempSync, openSync, readFileSync,
  readdirSync, realpathSync, renameSync, rmSync, statSync, writeFileSync, writeSync,
} from 'node:fs'
import { homedir, tmpdir } from 'node:os'
import { basename, delimiter, dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const REPO = process.env.LOOPTROOP_INSTALL_REPO || 'looptroop-ai/LoopTroop'
// Overridable so the tests can serve a fixture release index from localhost.
const API = process.env.LOOPTROOP_INSTALL_API || 'https://api.github.com'
const MANIFEST_ASSET = 'release-manifest.json'
const TARBALL_PATTERN = /^looptroop-.+\.tgz$/

/**
 * How long a transfer may make no progress before it is abandoned.
 *
 * Two numbers rather than one, because the two kinds of request fail
 * differently. Release metadata is a few hundred kilobytes: it either answers
 * promptly or something is wrong. An asset is up to ~110 MB and may legitimately
 * take many minutes on a domestic link, so what is bounded there is *silence*,
 * not duration — a deadline that restarts on every chunk refuses a connection
 * that died without putting a ceiling on a slow one that is working.
 *
 * Before these existed the installer had no timeout at all, so a stalled
 * connection was indistinguishable from an install in progress, forever.
 */
const METADATA_STALL_MS = 30_000
const DOWNLOAD_STALL_MS = 60_000

/**
 * How much of a response is read before it is refused.
 *
 * The largest thing a release publishes is a standalone archive of about
 * 110 MB, so 512 MiB is four times the largest legitimate payload — big enough
 * that no real release approaches it, small enough that a wrong URL cannot fill
 * this machine's disk or memory before the checksum gets a chance to object.
 */
const MAX_METADATA_BYTES = 32 * 1024 * 1024
const MAX_ASSET_BYTES = 512 * 1024 * 1024

/**
 * How to get a supported Node.
 *
 * The macOS line names the unversioned formula on purpose. `brew install
 * node@24` is keg-only — Homebrew installs it and deliberately does not link it
 * onto PATH, which is why LoopTroop's own tap has to wrap it — so a reader who
 * ran the versioned command would come back to the same "Node is not on your
 * PATH" message with Node installed. `brew install node` is linked, and is
 * always at or above a floor that names a released major.
 */
function nodeHelp(platform) {
  if (platform === 'darwin') return 'brew install node   (or download from https://nodejs.org/)'
  if (platform === 'win32') return 'winget install OpenJS.NodeJS.LTS   (or download from https://nodejs.org/)'
  return 'Use your distribution\'s package or https://github.com/nvm-sh/nvm'
}

/**
 * Refuses to go on, and says why.
 *
 * Thrown rather than `process.exit`ed. Calling `process.exit()` while a fetch
 * connection is still open crashes Node on Windows with 0xC0000409 instead of
 * exiting 1 — so a user who gave a bad checksum, or an old Node, saw a crash
 * where a message belonged. Unwinding to the top and letting the process end on
 * its own gets the message out and the exit code right on every platform.
 */
class InstallError extends Error {
  constructor(message, detail) {
    super(message)
    this.name = 'InstallError'
    this.detail = detail
  }
}

function fail(message, ...detail) {
  throw new InstallError(message, detail.filter(Boolean))
}

function say(message) {
  process.stdout.write(`${message}\n`)
}

// --- pure decisions -------------------------------------------------------

/**
 * Every option this installer accepts, in both spellings.
 *
 * One table rather than a list per file. The core parses `--version`, the
 * PowerShell wrapper's `param` block declares `-Version`, its forwarding block
 * maps one to the other, and the usage text prints whichever the reader typed.
 * Four places that have to agree about the same set, and they did not: the
 * wrapper forwarded four of the six, so `--dry-run` and `--help` were reachable
 * on macOS and Linux and silently absent on Windows. `tests/installer.test.ts`
 * reads this table and requires the wrapper to carry every row.
 */
export const INSTALL_OPTIONS = [
  {
    sh: '--version',
    ps: '-Version',
    value: 'X.Y.Z',
    help: 'install exactly this release, prereleases included',
  },
  {
    sh: '--tarball',
    ps: '-Tarball',
    value: 'PATH',
    help: 'install an already-downloaded tarball, skipping the network',
  },
  {
    sh: '--binary',
    ps: '-Binary',
    value: null,
    help: 'install the standalone executable instead of the npm package',
  },
  {
    sh: '--prefix',
    ps: '-Prefix',
    value: 'DIR',
    help: () => `where the standalone executable installs (default ${defaultPrefix()})`,
  },
  {
    sh: '--dry-run',
    ps: '-DryRun',
    value: null,
    help: 'say what would be downloaded and installed, then stop',
  },
  {
    sh: '--help',
    ps: '-Help',
    value: null,
    help: 'show this',
  },
]

/**
 * The usage text, in the dialect the reader actually typed.
 *
 * The wrappers take different spellings of one set of options, so a hardcoded
 * `Usage: install.sh` was wrong for everybody who reached this through
 * `install.ps1` — and wrong about every flag with it, since PowerShell does not
 * accept `--version`. The wrapper says which it is through the environment;
 * running the core directly gets the flags the core itself parses.
 */
export function usageLines(style = process.env.LOOPTROOP_INSTALL_STYLE === 'ps1' ? 'ps1' : 'sh') {
  const ps1 = style === 'ps1'
  const program = ps1 ? 'install.ps1' : 'install.sh'
  const spell = (option) => `${ps1 ? option.ps : option.sh}${option.value === null ? '' : ` ${option.value}`}`
  const find = (sh) => INSTALL_OPTIONS.find((option) => option.sh === sh)

  return [
    `Usage: ${program} [${spell(find('--version'))}] [${spell(find('--tarball'))}]`,
    `       ${program} ${spell(find('--binary'))} [${spell(find('--version'))}] [${spell(find('--prefix'))}]`,
    '',
    ...INSTALL_OPTIONS.map((option) => {
      const text = typeof option.help === 'function' ? option.help() : option.help
      return `  ${spell(option).padEnd(17)}${text}`
    }),
  ]
}

export function parseArgs(argv) {
  const options = { version: null, tarball: null, dryRun: false, binary: false, prefix: null }

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    const takeValue = () => {
      const value = argv[index + 1]
      if (value === undefined || value.startsWith('--')) fail(`${arg} needs a value.`)
      index += 1
      return value
    }

    switch (arg) {
      case '--version': options.version = takeValue().replace(/^v/, ''); break
      case '--tarball': options.tarball = takeValue(); break
      case '--dry-run': options.dryRun = true; break
      case '--binary': options.binary = true; break
      case '--prefix': options.prefix = takeValue(); break
      case '--help':
      case '-h':
        for (const line of usageLines()) say(line)
        process.exit(0)
        break
      default:
        fail(`Unknown option ${arg}.`, 'Run with --help to see what is accepted.')
    }
  }

  // Two different installers, and `--tarball` names an npm tarball. Silently
  // preferring one would install something other than what was asked for.
  if (options.binary && options.tarball !== null) {
    fail('--binary and --tarball cannot be combined.', '--tarball installs an npm tarball; --binary installs the standalone executable.')
  }
  if (options.prefix !== null && !options.binary) {
    fail('--prefix applies only to --binary.', 'The npm install goes wherever npm\'s global prefix points; change it with `npm config set prefix`.')
  }

  return options
}

/**
 * The build of the standalone executable that runs here, or why there is none.
 *
 * Refusing is a first-class outcome rather than an error path. Every one of
 * these platforms has a working LoopTroop through some other channel, so the
 * answer a user needs is which one — not that this failed.
 *
 * `libc` is passed in rather than probed so the refusal can be tested from any
 * machine; `detectLibc` supplies it in real use.
 */
export function binaryTarget(platform, arch, libc = 'glibc') {
  const elsewhere = [
    'LoopTroop still installs here through npm:',
    '  npm install -g looptroop',
  ]

  if (platform === 'darwin' && arch === 'x64') {
    return {
      refusal: [
        'There is no standalone executable for Intel Macs.',
        'Node cannot build a single-file executable for darwin-x64 at all — the feature',
        'supports arm64 only — so this is a gap in the runtime, not a build we skipped.',
        '',
        'On an Intel Mac, use Homebrew or npm:',
        '  brew install looptroop-ai/tap/looptroop',
        '  npm install -g looptroop',
      ],
    }
  }

  if (platform === 'linux' && libc === 'musl') {
    return {
      refusal: [
        'There is no standalone executable for musl systems such as Alpine.',
        'Node\'s single-file executables are built against glibc and will not run here.',
        '',
        ...elsewhere,
        '',
        'Or run the container image, which carries everything it needs:',
        '  docker run looptroopai/looptroop:latest',
      ],
    }
  }

  const known = {
    'linux-x64': 'linux-x64',
    'linux-arm64': 'linux-arm64',
    'darwin-arm64': 'darwin-arm64',
    'win32-x64': 'win-x64',
  }
  const target = known[`${platform}-${arch}`]
  if (target !== undefined) return { target }

  return {
    refusal: [
      `There is no standalone executable for ${platform}-${arch}.`,
      'The executables are built for linux-x64, linux-arm64, darwin-arm64 and win-x64.',
      '',
      ...elsewhere,
    ],
  }
}

/**
 * glibc or musl.
 *
 * Node's own report carries the runtime glibc version on a glibc system and
 * omits the field entirely on musl, which is the only detection that does not
 * involve running `ldd` and parsing its output — and `ldd` is itself absent from
 * a minimal musl image.
 */
export function detectLibc(report = process.report?.getReport?.()) {
  if (process.platform !== 'linux') return 'glibc'
  return report?.header?.glibcVersionRuntime ? 'glibc' : 'musl'
}

/** What a release calls the standalone archive for a target. */
export function binaryAssetName(version, target) {
  return `looptroop-${version}-${target}${target.startsWith('win') ? '.zip' : '.tar.gz'}`
}

/**
 * The assets a `--binary` install needs, or null.
 *
 * The manifest is as necessary here as for the npm path: it is what carries the
 * checksum, and an archive installed without one is an archive taken on trust
 * from a URL. Releases published before the executables existed carry neither,
 * and are simply not candidates.
 */
export function binaryAssets(release, target) {
  const assets = Array.isArray(release.assets) ? release.assets : []
  const manifest = assets.find((asset) => asset.name === MANIFEST_ASSET)
  const wanted = binaryAssetName(versionOf(release), target)
  const archive = assets.find((asset) => asset.name === wanted)
  return manifest && archive ? { manifest, archive } : null
}

/**
 * Where `--binary` installs when nobody says otherwise.
 *
 * Its own directory rather than somewhere already on PATH, because this mode
 * writes a program *and* the licences that must travel with it — redistributing
 * Node obliges us to ship Node's — and scattering those through `~/.local/bin`
 * would be litter. The same shape `rustup`, `deno` and `bun` use.
 */
export function defaultPrefix(env = process.env, home = homedir()) {
  return env.LOOPTROOP_INSTALL_DIR || join(home, '.looptroop')
}

/** True when `dir` is already on this PATH, so the closing advice can be honest. */
export function onPath(dir, pathValue = process.env.PATH || '') {
  const normalise = (value) => (process.platform === 'win32' ? value.toLowerCase() : value).replace(/[\\/]+$/, '')
  return pathValue.split(delimiter).filter(Boolean).map(normalise).includes(normalise(dir))
}

/**
 * Semver ordering, prereleases below the release they precede.
 *
 * Only what release tags actually use: numeric core plus a dot-separated
 * prerelease, compared numerically where both parts are numeric and
 * lexically otherwise, as the spec requires.
 */
export function compareVersions(left, right) {
  const split = (value) => {
    const [core, pre = null] = String(value).replace(/^v/, '').split('-', 2)
    return { core: core.split('.').map((part) => Number.parseInt(part, 10) || 0), pre }
  }

  const a = split(left)
  const b = split(right)

  for (let index = 0; index < Math.max(a.core.length, b.core.length); index += 1) {
    const difference = (a.core[index] ?? 0) - (b.core[index] ?? 0)
    if (difference !== 0) return difference < 0 ? -1 : 1
  }

  if (a.pre === b.pre) return 0
  if (a.pre === null) return 1
  if (b.pre === null) return -1

  const aParts = a.pre.split('.')
  const bParts = b.pre.split('.')
  for (let index = 0; index < Math.max(aParts.length, bParts.length); index += 1) {
    const x = aParts[index]
    const y = bParts[index]
    if (x === y) continue
    if (x === undefined) return -1
    if (y === undefined) return 1
    const numeric = /^\d+$/.test(x) && /^\d+$/.test(y)
    if (numeric) return Number(x) - Number(y) < 0 ? -1 : 1
    return x < y ? -1 : 1
  }

  return 0
}

export function versionOf(release) {
  return String(release.tag_name ?? '').replace(/^v/, '')
}

/** The assets an install needs; a release without both is not installable. */
export function installableAssets(release) {
  const assets = Array.isArray(release.assets) ? release.assets : []
  const manifest = assets.find((asset) => asset.name === MANIFEST_ASSET)
  const tarball = assets.find((asset) => TARBALL_PATTERN.test(String(asset.name)))
  return manifest && tarball ? { manifest, tarball } : null
}

/**
 * The release to install: the pinned one, or the newest stable that can
 * actually be installed.
 *
 * "That can actually be installed" is not pedantry. An early release was
 * published with no assets at all, so a walk that stopped at the newest stable
 * tag would resolve to a release with nothing to download — and would do so
 * again for any future release whose asset upload failed halfway.
 *
 * `installable` is a parameter because "installable" means something different
 * per mode: every release since the first carries an npm tarball, but only
 * releases since the executables existed carry an archive for this target, and
 * `--binary` must walk past the ones that do not rather than resolve to a
 * release it cannot install from.
 */
export function selectRelease(releases, pinned = null, installable = installableAssets) {
  const candidates = releases
    .filter((release) => release && release.draft !== true)
    .filter((release) => (pinned === null ? release.prerelease !== true : versionOf(release) === pinned))
    .filter((release) => installable(release) !== null)

  candidates.sort((a, b) => compareVersions(versionOf(b), versionOf(a)))
  return candidates[0] ?? null
}

/**
 * True when `have` satisfies a `>=x.y.z` style floor.
 *
 * An unreadable floor is not "no floor": stripping `not-a-range` down to
 * leftover text and treating that as a zero version accepts every runtime.
 * Same grammar as `parseNodeFloor` — three numeric components, no prerelease
 * suffix — so a malformed manifest fails the install rather than skipping it.
 */
export function satisfiesFloor(have, floor) {
  const match = /^\s*(?:>=\s*)?v?(\d+)\.(\d+)\.(\d+)\s*$/.exec(String(floor))
  if (!match) return false
  return compareVersions(have, `${match[1]}.${match[2]}.${match[3]}`) >= 0
}

// --- effects --------------------------------------------------------------

/**
 * A deadline that restarts every time bytes arrive.
 *
 * `AbortSignal.timeout` would bound the whole request instead, which for a
 * 110 MB archive means choosing between a limit long enough that a dead
 * connection hangs for minutes and one short enough to abandon a slow but
 * working download. What actually goes wrong is a transfer that stops
 * progressing, and that is what this measures.
 */
export function stallGuard(idleMs, what) {
  const controller = new AbortController()
  let timer = null

  const arm = () => {
    clearTimeout(timer)
    timer = setTimeout(() => {
      controller.abort(new Error(`${what} made no progress for ${Math.round(idleMs / 1000)}s.`))
    }, idleMs)
    // Nothing should stay alive merely because this timer is pending.
    timer.unref?.()
  }

  arm()
  return {
    signal: controller.signal,
    touch: arm,
    release: () => clearTimeout(timer),
    /** The abort reason if this guard fired, so the message says "stalled" rather than "aborted". */
    reason: () => (controller.signal.aborted ? String(controller.signal.reason?.message ?? controller.signal.reason) : null),
  }
}

/**
 * Every byte of a response, up to `limit`, handed to `write` as it arrives.
 *
 * `arrayBuffer()` is shorter and is what this used to do, but it buffers
 * whatever the other end sends before anything can object — so the checksum
 * that exists to catch a wrong file only ran once the wrong file was entirely
 * in memory. The declared length is refused up front when there is one, and the
 * running total is checked either way, because a chunked response declares no
 * length at all.
 */
export async function streamBody(response, limit, what, write, touch) {
  const declared = Number(response.headers.get('content-length') ?? Number.NaN)
  if (Number.isFinite(declared) && declared > limit) {
    fail(`${what} declares ${declared} bytes, and this installer reads at most ${limit}.`, 'Nothing was installed.')
  }

  const reader = response.body?.getReader()
  if (reader === undefined) fail(`${what} arrived with no body.`, 'Nothing was installed.')

  let total = 0
  for (;;) {
    const { done, value } = await reader.read()
    if (done) break
    touch()
    total += value.byteLength
    if (total > limit) {
      await reader.cancel().catch(() => {})
      fail(`${what} is larger than the ${limit} bytes this installer reads.`, 'Nothing was installed.')
    }
    write(Buffer.from(value.buffer, value.byteOffset, value.byteLength))
  }
  return total
}

async function getJson(url) {
  const headers = { accept: 'application/vnd.github+json', 'user-agent': 'looptroop-installer' }
  // Only to lift the 60-per-hour anonymous rate limit when one happens to be
  // present, as in CI. Never required, never printed.
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN
  if (token) headers.authorization = `Bearer ${token}`

  const guard = stallGuard(METADATA_STALL_MS, 'The request to GitHub')
  try {
    let response
    try {
      response = await fetch(url, { headers, signal: guard.signal })
    } catch (error) {
      fail('Could not reach GitHub.', guard.reason() ?? String(error.message ?? error), 'Check your network and try again.')
    }
    if (!response.ok) {
      fail(
        `GitHub answered ${response.status} for the release list.`,
        response.status === 403 ? 'That is usually the anonymous rate limit; try again in a few minutes.' : '',
      )
    }

    const chunks = []
    try {
      await streamBody(response, MAX_METADATA_BYTES, 'The release list', (chunk) => chunks.push(chunk), guard.touch)
    } catch (error) {
      if (error instanceof InstallError) throw error
      fail('Could not read GitHub\'s answer.', guard.reason() ?? String(error.message ?? error))
    }

    try {
      return JSON.parse(Buffer.concat(chunks).toString('utf8'))
    } catch {
      fail('GitHub answered with something that is not JSON.', 'Try again in a few minutes.')
    }
  } finally {
    guard.release()
  }
}

async function download(url, destination) {
  const guard = stallGuard(DOWNLOAD_STALL_MS, `Downloading ${basename(destination)}`)
  let handle = null

  try {
    let response
    try {
      response = await fetch(url, {
        headers: { 'user-agent': 'looptroop-installer' },
        redirect: 'follow',
        signal: guard.signal,
      })
    } catch (error) {
      fail(`Downloading ${basename(destination)} failed.`, guard.reason() ?? String(error.message ?? error))
    }
    if (!response.ok) fail(`Downloading ${basename(destination)} failed with ${response.status}.`)

    handle = openSync(destination, 'w')
    try {
      await streamBody(response, MAX_ASSET_BYTES, basename(destination), (chunk) => writeSync(handle, chunk), guard.touch)
    } catch (error) {
      if (error instanceof InstallError) throw error
      fail(`Downloading ${basename(destination)} failed.`, guard.reason() ?? String(error.message ?? error))
    }
  } catch (error) {
    // A half-written file is worse than none: the next run would hash it,
    // reject it against the release's checksum, and report a corrupt release
    // rather than an interrupted download.
    if (handle !== null) {
      closeSync(handle)
      handle = null
    }
    discard(destination)
    throw error
  } finally {
    if (handle !== null) closeSync(handle)
    guard.release()
  }
}

/**
 * Where PATH resolves `command` on Windows, with PATHEXT applied.
 *
 * The same search `CreateProcess` would do, done here so the answer can be
 * looked at: whether what PATH resolves to is a real executable or a batch
 * shim decides how it has to be launched, and there is no way to launch it
 * correctly without knowing which.
 */
function resolveOnPath(command) {
  const extensions = (process.env.PATHEXT || '.COM;.EXE;.BAT;.CMD').split(';').filter(Boolean)
  for (const directory of (process.env.PATH || '').split(delimiter).filter(Boolean)) {
    for (const extension of ['', ...extensions]) {
      const candidate = join(directory, `${command}${extension}`)
      if (statSync(candidate, { throwIfNoEntry: false })?.isFile()) return candidate
    }
  }
  return null
}

/** Every argument as one cmd.exe token, whatever it contains. */
export function quoteForCmd(value) {
  return `"${String(value).replace(/"/g, '""')}"`
}

/**
 * Runs a command without a shell re-reading its arguments.
 *
 * `shell: true` on Windows was the previous answer and it is wrong in a way
 * that bites ordinary machines. Node joins the file and arguments with spaces
 * and quotes none of them, so `npm install -g C:\Users\Ada Lovelace\AppData\
 * Local\Temp\looptroop-install-x\looptroop-1.2.3.tgz` reached npm as four
 * arguments — every account whose name contains a space, which is most of them.
 * The same re-parsing is what lets a path be read as a shell operator.
 *
 * A shell is needed on Windows for one reason only: `npm` and `looptroop` are
 * `.cmd` shims there, batch files rather than executable images, and Node has
 * refused to spawn one without a shell since the BatBadBut fix. So the shell is
 * used only when PATH actually resolves to a shim, and its command line is
 * built here with explicit quoting rather than by joining on spaces.
 *
 * `smoke-published.mjs` carries the same helper. It is repeated rather than
 * imported because this file is embedded verbatim into `install.sh` and
 * `install.ps1` and cannot import anything at all.
 */
function runTool(command, args, options = {}) {
  if (process.platform !== 'win32') {
    return spawnSync(command, args, { ...options, shell: false })
  }

  const resolved = resolveOnPath(command)
  // Not found, or a real executable image: spawn it directly. Leaving an
  // unresolved name to fail as ENOENT is deliberate — the caller's own message
  // about a missing tool is better than one invented here.
  if (resolved === null || !/\.(cmd|bat)$/i.test(resolved)) {
    return spawnSync(resolved ?? command, args, { ...options, shell: false })
  }

  // `/d` skips AutoRun commands from the registry, `/s` makes cmd strip only
  // the outermost pair of quotes and take the rest verbatim, and
  // `windowsVerbatimArguments` stops Node adding a second layer of its own.
  const line = `"${[resolved, ...args].map(quoteForCmd).join(' ')}"`
  return spawnSync(process.env.ComSpec || 'cmd.exe', ['/d', '/s', '/c', line], {
    ...options,
    shell: false,
    windowsVerbatimArguments: true,
  })
}

function npmVersion() {
  const probe = runTool('npm', ['--version'], { encoding: 'utf8' })
  return probe.status === 0 ? String(probe.stdout).trim() : null
}

/**
 * Checked against the floor the release itself records, not one baked in here:
 * an installer that hardcodes the requirement is wrong for every release but
 * the one it shipped with. Manifests written before `engines` existed simply
 * carry no floor, and are not treated as failing one.
 */
function checkRuntime(engines) {
  if (!engines) return

  if (engines.node && !satisfiesFloor(process.versions.node, engines.node)) {
    fail(
      `LoopTroop needs Node ${engines.node}; this is ${process.versions.node}.`,
      nodeHelp(process.platform),
      'LoopTroop will not install Node for you.',
    )
  }

  const npm = npmVersion()
  if (npm === null) fail('npm is not on PATH, and installing needs it.', 'It ships with Node; reinstall Node.')
  if (engines.npm && !satisfiesFloor(npm, engines.npm)) {
    fail(`LoopTroop needs npm ${engines.npm}; this is ${npm}.`, `Upgrade with: npm install -g npm@${engines.npm.replace(/^[^\d]*/, '')}`)
  }
}

function verifyBytes(file, manifest) {
  const bytes = readFileSync(file)
  const sha256 = createHash('sha256').update(bytes).digest('hex')

  if (typeof manifest.bytes === 'number' && bytes.length !== manifest.bytes) {
    fail(`${basename(file)} is ${bytes.length} bytes; the release records ${manifest.bytes}.`, 'Nothing was installed.')
  }
  if (sha256 !== manifest.sha256) {
    fail(
      `${basename(file)} does not match the checksum this release published.`,
      `computed ${sha256}`,
      `expected ${manifest.sha256}`,
      'Nothing was installed.',
    )
  }

  say(`Verified sha256 ${sha256}`)
}

function installGlobally(tarball) {
  say(`Installing with npm...`)
  const result = runTool('npm', ['install', '-g', tarball, '--no-audit', '--no-fund'], {
    stdio: 'inherit',
  })

  if (result.status !== 0) {
    fail(
      'npm could not install LoopTroop globally.',
      'If that was a permissions error, point npm at a directory you own rather than using sudo:',
      '  npm config set prefix ~/.npm-global',
      '  export PATH="$HOME/.npm-global/bin:$PATH"',
    )
  }
}

// --- the standalone executable ---------------------------------------------
//
// Everything below exists because this mode unpacks files itself. The npm path
// hands the hard parts to npm; this one owns them, and each of these steps is
// here because skipping it breaks an *upgrade* rather than a first install —
// which is the case that matters, since it lands on somebody already using the
// program.

const EXE = process.platform === 'win32' ? '.exe' : ''

/**
 * Removes something if it can, and never throws. A leftover is not a failure.
 *
 * Retried, because most of what this removes is an executable that was running
 * moments ago and Windows does not release a handle the instant a process
 * exits. `force` swallows ENOENT and nothing else, so without the retries a
 * successful install could end by reporting EPERM.
 */
function discard(path) {
  try {
    rmSync(path, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 })
    return true
  } catch {
    return false
  }
}

/**
 * Unpacks the release archive.
 *
 * `tar` reads both formats on all three platforms — GNU tar on Linux, bsdtar on
 * macOS, and bsdtar shipped with Windows since 1803, which reads zip too — and
 * all of them detect the compression from the file rather than the flags.
 * PowerShell is the fallback for a Windows old enough to lack it.
 */
function extractArchive(archive, into) {
  mkdirSync(into, { recursive: true })

  const tar = spawnSync('tar', ['-xf', archive, '-C', into], { encoding: 'utf8' })
  if (tar.status === 0) return

  if (process.platform === 'win32') {
    const quote = (value) => `'${value.replace(/'/g, "''")}'`
    const powershell = spawnSync('powershell', [
      '-NoProfile', '-NonInteractive', '-Command',
      `Expand-Archive -LiteralPath ${quote(archive)} -DestinationPath ${quote(into)} -Force`,
    ], { encoding: 'utf8' })
    if (powershell.status === 0) return
  }

  fail(
    `Could not unpack ${basename(archive)}.`,
    String(tar.stderr || tar.error?.message || '').trim(),
    'Nothing was installed.',
  )
}

/**
 * Runs `action` with nobody else installing into `dir` at the same time.
 *
 * Two installers in one directory is not hypothetical — a user re-running a
 * curl pipe because the first looked stuck is exactly how it happens — and the
 * interleaving that costs you is one process renaming the backup into place
 * while the other is mid-swap, which ends with no working executable at all.
 *
 * A lock left by a killed process would otherwise wedge the directory forever,
 * so one older than the longest plausible install is taken rather than obeyed.
 */
function withInstallLock(dir, action) {
  const lock = join(dir, '.install.lock')
  const STALE_AFTER = 15 * 60 * 1000
  // Not the pid: pids are reused, and two installers started a second apart on
  // a busy machine can hold the same one after a wrap. A token nobody else can
  // reproduce makes "is this still my lock?" answerable.
  const token = `${process.pid}-${randomUUID()}`

  const take = () => {
    writeFileSync(lock, `${token} ${new Date().toISOString()}\n`, { flag: 'wx' })
  }
  const holdsOurs = () => {
    try {
      return readFileSync(lock, 'utf8').startsWith(`${token} `)
    } catch {
      return false
    }
  }

  /**
   * Clears a lock left by a killed run, or refuses.
   *
   * The obvious version — see it is old, delete it, create a new one — is not
   * safe with two installers in the directory: both see the same stale lock,
   * both delete it, both create one, and the second deletes the first's *new*
   * lock on its way past. Both then believe they hold it.
   *
   * `rename` is the fix, because exactly one process can rename a given file:
   * whoever wins takes custody of the old lock and the losers get ENOENT and
   * fall through to `take()`, where `wx` decides between them. Custody also
   * makes the staleness test sound — the age is read from a file nobody else
   * can still be touching — and a lock that turns out to be fresh is renamed
   * back rather than destroyed.
   */
  const clearStaleLock = () => {
    const observed = statSync(lock, { throwIfNoEntry: false })
    if (observed === undefined) return
    if (Date.now() - observed.mtimeMs < STALE_AFTER) {
      fail(
        'Another install is already running in this directory.',
        `Its lock is at ${lock}.`,
        'Wait for it to finish, or delete that file if you are sure nothing is running.',
      )
    }

    const aside = `${lock}.stale-${token}`
    try {
      renameSync(lock, aside)
    } catch (error) {
      // Somebody else got there first. Their `take()` and ours now race on
      // `wx`, which is exactly the outcome this is trying to reach.
      if (error.code === 'ENOENT') return
      throw error
    }

    const owned = statSync(aside, { throwIfNoEntry: false })
    const age = Date.now() - (owned?.mtimeMs ?? 0)
    if (owned !== undefined && age < STALE_AFTER) {
      // It was refreshed between the check above and the rename, so it belongs
      // to a live install after all. Put it back before refusing.
      renameSync(aside, lock)
      fail(
        'Another install is already running in this directory.',
        `Its lock is at ${lock}.`,
        'Wait for it to finish, or delete that file if you are sure nothing is running.',
      )
    }

    say(`Clearing a stale install lock (${Math.round(age / 60000)} minutes old).`)
    discard(aside)
  }

  try {
    take()
  } catch (error) {
    if (error.code !== 'EEXIST') throw error
    clearStaleLock()
    try {
      take()
    } catch (retry) {
      if (retry.code !== 'EEXIST') throw retry
      fail(
        'Another install took the lock in this directory first.',
        `Its lock is at ${lock}.`,
        'Wait for it to finish and run this again.',
      )
    }
  }

  try {
    return action()
  } finally {
    // Only ours. Removing a lock we do not hold is the same mistake the
    // takeover above exists to prevent, reached from the other end.
    if (holdsOurs()) discard(lock)
  }
}

/** What the installed copy says about the daemon, or null if it cannot say. */
function daemonRunning(binary) {
  // The exit code is not the answer — `status` reports a stopped daemon by
  // saying so, and how it scores that is its business — so this reads the
  // document and ignores the code.
  const probe = spawnSync(binary, ['status', '--json'], { encoding: 'utf8', timeout: 30_000 })
  try {
    return JSON.parse(probe.stdout).running === true
  } catch {
    return null
  }
}

/** True when the executable at `binary` runs at all. */
function executableRuns(binary) {
  return spawnSync(binary, ['--version'], { encoding: 'utf8', timeout: 60_000 }).status === 0
}

/**
 * Stops the daemon and waits for it to actually be gone.
 *
 * "Confirm exit" rather than "ask it to stop": on Windows the file cannot be
 * replaced while a process holds it open, and on every platform an upgrade that
 * swaps the executable under a live daemon leaves a running old version that
 * `--version` will cheerfully misreport as the new one.
 *
 * Confirmed *stopped*, not merely "not confirmed running". `daemonRunning` has
 * three answers and this used to accept two of them, so a probe that could not
 * say anything counted as success and the swap went ahead under a daemon nobody
 * had established was down.
 */
function stopDaemon(binary) {
  say('Stopping the running daemon...')
  spawnSync(binary, ['stop'], { stdio: 'inherit', timeout: 60_000 })

  return waitFor(() => daemonRunning(binary) === false, 30_000)
}

/**
 * Brings the installed copy to a state where replacing it is safe, and says
 * whether its daemon has to be running again afterwards.
 *
 * The three answers of `daemonRunning` need three branches, and treating the
 * third as "stopped" was the bug: an upgrade could swap the executable under a
 * live daemon and then not restart it, leaving the old version serving while
 * `looptroop --version` reported the new one.
 *
 * The unknown case is resolved rather than refused. Refusing would be the
 * strictest reading, but it wedges the one person who most needs to reinstall —
 * somebody whose installed executable is broken can never make it answer a
 * probe, and so could never install over it. So: an executable that cannot even
 * print its own version is not serving anything and is replaced; one that runs
 * but will not report is asked to stop and must then *confirm* it is stopped,
 * and is started again afterwards because this may well have taken a live
 * service down.
 */
function settleDaemon(installed) {
  const state = daemonRunning(installed)

  if (state === true) {
    if (!stopDaemon(installed)) {
      fail(
        'The LoopTroop daemon did not stop, so the executable was left alone.',
        'Stop it yourself and run this again:',
        `  ${installed} stop`,
        'Nothing was installed.',
      )
    }
    return { wasRunning: true }
  }

  if (state === false) return { wasRunning: false }

  if (!executableRuns(installed)) {
    say('The installed copy does not run, so there is no daemon of its to stop.')
    return { wasRunning: false }
  }

  say('The installed copy would not report whether its daemon is running; stopping it to be sure...')
  spawnSync(installed, ['stop'], { stdio: 'inherit', timeout: 60_000 })

  // Not `stopDaemon`, which requires a *confirmed* stopped state. A copy whose
  // `status` output cannot be read will never confirm anything, so demanding it
  // here would wedge the upgrade forever rather than once — and the state it
  // refuses over is the state this branch started in. What can still be
  // established is the opposite: if it now says outright that it is running,
  // the swap must not happen.
  if (!waitFor(() => daemonRunning(installed) !== true, 30_000)) {
    fail(
      'The LoopTroop daemon is still running after being asked to stop.',
      'Replacing the executable now would leave the old version serving and reporting the new one\'s version.',
      'Stop it yourself and run this again:',
      `  ${installed} stop`,
      'Nothing was installed.',
    )
  }

  // It was asked to stop from an unknown state, so it may well have been
  // serving. Starting it again is the outcome that cannot leave an outage.
  return { wasRunning: true }
}

/**
 * Starts the daemon and waits until it is actually answering.
 *
 * The exit code of `start` is not the answer. It detaches, so it can report
 * success and then die a second later — and this is called at the point where
 * the difference decides whether an upgrade rolls back.
 */
function startDaemon(binary) {
  spawnSync(binary, ['start'], { stdio: 'inherit', timeout: 120_000 })

  // 30s: a daemon that is coming up answers in about two, so this is already
  // an order of magnitude of headroom. Waiting longer would not rescue a build
  // that is going to fail — it would only make every rollback slower to reach.
  return waitFor(() => daemonRunning(binary) === true, 30_000)
}

/** Polls until `condition` holds, or gives up. */
function waitFor(condition, timeoutMs) {
  const deadline = Date.now() + timeoutMs
  for (;;) {
    if (condition()) return true
    if (Date.now() >= deadline) return false
    // No timers: this is a synchronous stretch, and `Atomics.wait` is the one
    // sleep that does not need the event loop to turn.
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 500)
  }
}

/**
 * Puts `staged` at `installed`, keeping whatever was there until the new one
 * has proved it runs.
 *
 * Two renames rather than a copy over the top. `rename` within a directory is
 * atomic, so no reader ever sees a half-written file, and it is the one
 * operation permitted on a *running* executable on Windows — which cannot be
 * overwritten or deleted, but can be moved out of the way.
 */
function swapIntoPlace(staged, installed, backup) {
  const incoming = `${installed}.incoming-${process.pid}`

  // Copied into the destination directory first so the rename that matters is
  // same-filesystem. Across devices `rename` is EXDEV, and the fallback for
  // that is a copy — which is exactly the non-atomic write being avoided.
  copyFileSync(staged, incoming)
  chmodSync(incoming, 0o755)

  const had = existsSync(installed)
  if (had) renameSync(installed, backup)

  try {
    renameSync(incoming, installed)
  } catch (error) {
    discard(incoming)
    if (had) renameSync(backup, installed)
    throw error
  }

  return had
}

/**
 * Installs the standalone executable, transactionally.
 *
 * Transactional meaning: at every moment during this, `looptroop` on the user's
 * PATH is either the old working version or the new working version. There is
 * no window where it is a half-written file, and no outcome where a failure
 * partway leaves nothing installed.
 */
function installBinary(archive, { version, prefix }) {
  const bin = join(prefix, 'bin')
  mkdirSync(bin, { recursive: true })

  return withInstallLock(prefix, () => {
    const installed = join(bin, `looptroop${EXE}`)
    const backup = join(bin, `.looptroop-previous-${process.pid}${EXE}`)

    // Anything an earlier run left behind: a backup or a staging copy from one
    // that was killed, and the rejected executable from one that rolled back.
    // Sweeping at the start rather than the end is what bounds this to a single
    // leftover — the most recent failure stays inspectable, which is the one
    // anybody would want, and the ~110 MB before it does not accumulate.
    //
    // Not fatal if something will not go. A leftover is inert, and refusing an
    // install over one would be worse than leaving it.
    for (const entry of readdirSync(bin)) {
      if (/^\.looptroop-previous-\d+/.test(entry) || /\.(incoming|rejected)-\d+$/.test(entry)) {
        discard(join(bin, entry))
      }
    }

    const unpacked = join(dirname(archive), 'unpacked')
    extractArchive(archive, unpacked)

    const root = join(unpacked, basename(archive).replace(/\.(tar\.gz|zip)$/, ''))
    const staged = join(root, `looptroop${EXE}`)
    if (!statSync(staged, { throwIfNoEntry: false })?.isFile()) {
      fail(`${basename(archive)} does not contain looptroop${EXE} where it should.`, 'Nothing was installed.')
    }

    const { wasRunning } = existsSync(installed) ? settleDaemon(installed) : { wasRunning: false }

    let replaced
    try {
      replaced = swapIntoPlace(staged, installed, backup)
    } catch (error) {
      // `swapIntoPlace` already put the old executable back, but the daemon was
      // stopped before it ran — so leaving here without starting it again is the
      // same outage the rollback path exists to prevent, reached by a different
      // route. Windows makes this the *likeliest* route, not a remote one: it is
      // where a locked file lands.
      const restored = wasRunning ? startDaemon(installed) : null

      fail(
        `Could not replace ${installed}.`,
        String(error.message ?? error),
        process.platform === 'win32'
          ? 'On Windows a running program cannot be replaced; check nothing else is using it.'
          : '',
        'Nothing was installed; the previous version is untouched.',
        restored === true ? 'Its daemon is running again.' : '',
        restored === false
          ? `Its daemon did not start again. Start it with: ${installed} start`
          : '',
      )
    }

    // The install is not finished until the thing that was installed runs. A
    // truncated download is caught by the checksum, but an executable that is
    // whole and still cannot start here — wrong architecture, a macOS signature
    // the kernel refuses, a missing glibc symbol — passes every earlier check
    // and fails at the only moment the user is watching.
    /**
     * Undoes the swap and puts the user back where they started — *including*
     * the daemon.
     *
     * Restoring the executable is only half of it. This ran `stop` on a service
     * that was up, so a rollback that restores the file and returns leaves the
     * old version installed and not running, which is an outage caused by an
     * upgrade that reported failure — the worst of both. The restart is
     * therefore part of the rollback, and whether it worked is reported rather
     * than assumed.
     */
    const rollBack = (reason, ...detail) => {
      const quarantine = `${installed}.rejected-${process.pid}`
      discard(quarantine)
      renameSync(installed, quarantine)
      if (replaced) renameSync(backup, installed)

      const restored = replaced && wasRunning ? startDaemon(installed) : null

      fail(
        reason,
        ...detail,
        replaced ? 'Your previous version is back in place.' : '',
        restored === true ? 'It is running again.' : '',
        restored === false
          ? `It did not start again. Start it yourself with: ${installed} start`
          : '',
        `The rejected file is at ${quarantine} if you want to look at it.`,
      )
    }

    const probe = spawnSync(installed, ['--version'], { encoding: 'utf8', timeout: 60_000 })
    const reported = probe.status === 0 ? String(probe.stdout).trim() : null

    if (reported !== version) {
      rollBack(
        replaced
          ? `The new executable did not run, so ${version} was rolled back.`
          : 'The downloaded executable does not run here.',
        reported === null
          ? `\`looptroop --version\` exited ${String(probe.status ?? probe.signal)}: ${String(probe.stderr || probe.error?.message || '').trim().slice(0, 400)}`
          : `\`looptroop --version\` reported ${reported}, expected ${version}.`,
      )
    }

    // Restarted here rather than after this function returns, because here the
    // backup still exists and the lock is still held. `--version` succeeding
    // proves the file runs; it does not prove the daemon comes up, and those
    // are different failures — a build that starts and immediately exits passes
    // the first and fails the second. Confirming it before discarding the only
    // copy of the working version is what makes this an upgrade you can undo.
    if (wasRunning) {
      say('Starting it again...')
      if (!startDaemon(installed)) {
        rollBack(
          `${version} installed but its daemon would not start, so it was rolled back.`,
          'The executable runs and reports the right version; it does not stay up.',
        )
      }
    }

    // Node's licence travels with Node, and this archive carries a copy of Node.
    // It goes beside the program because that is where it has to be for the
    // install to be a lawful redistribution, not because anyone will read it.
    //
    // Copied here, after the executable transaction has committed, rather than
    // before it. Copied first, every one of these files landed in the prefix
    // ahead of the daemon check, the swap, the version probe and the restart —
    // so a rollback restored the executable and said "your previous version is
    // back in place" beside the *new* version's licences and notices. The
    // executable is the only thing with a rollback, so it is the only thing
    // that may be written before the install is known to have worked.
    const strays = []
    for (const file of readdirSync(root)) {
      if (file === `looptroop${EXE}`) continue
      try {
        copyFileSync(join(root, file), join(prefix, file))
      } catch {
        strays.push(file)
      }
    }
    if (strays.length > 0) {
      // Not a rollback. The program is installed, verified and running; what
      // failed is documentation that travels beside it, and undoing a working
      // upgrade over that would be the worse outcome. Said out loud so it is
      // not a silent omission.
      say(`Note: could not update ${strays.join(', ')} in ${prefix}.`)
    }

    discard(backup)
    return { installed, wasRunning }
  })
}

async function main(argv) {
  const options = parseArgs(argv)
  const workDir = mkdtempSync(resolve(tmpdir(), 'looptroop-install-'))

  // A signal is not an error this can unwind through: the process ends where it
  // stands, so the `finally` below never runs and an interrupted install leaves
  // its downloads behind. Every one of these leaks a directory that may hold a
  // 110 MB archive, and Ctrl+C during a download is the ordinary way somebody
  // changes their mind.
  //
  // Re-raised rather than exited, with the listener removed first so the second
  // delivery takes the default action. A caller that sent a signal expects the
  // 128+signal status back, not an ordinary exit code chosen here.
  for (const signal of ['SIGINT', 'SIGTERM', 'SIGHUP']) {
    process.on(signal, () => {
      discard(workDir)
      process.removeAllListeners(signal)
      process.kill(process.pid, signal)
    })
  }
  // What we resolved and installed, so the closing message can be checked
  // against it. Stays null for `--tarball`, where a local file is taken on
  // trust and there is no release to name a version.
  let intended = null
  // How to get `looptroop` on PATH, which is a different answer per mode: npm
  // has a global bin directory it can be asked about, and `--binary` has one we
  // chose. Filled in by whichever branch runs.
  let pathAdvice = [
    'Open a new terminal, or add npm\'s global bin directory to PATH: npm prefix -g',
  ]
  // Where this run put the program, when it chose. Null for the npm path, where
  // npm chose and the honest answer is `npm prefix -g`.
  let installedPath = null

  try {
    if (options.binary) {
      const decision = binaryTarget(process.platform, process.arch, detectLibc())
      if (decision.refusal) fail('There is no standalone executable for this platform.', ...decision.refusal)

      const prefix = resolve(options.prefix ?? defaultPrefix())
      const url = options.version === null
        ? `${API}/repos/${REPO}/releases?per_page=100`
        : `${API}/repos/${REPO}/releases/tags/v${options.version}`
      const payload = await getJson(url)
      const releases = Array.isArray(payload) ? payload : [payload]

      const release = selectRelease(releases, options.version, (candidate) => binaryAssets(candidate, decision.target))
      if (release === null) {
        fail(
          options.version === null
            ? `No published release carries a ${decision.target} executable yet.`
            : `Release v${options.version} carries no ${decision.target} executable.`,
          `Looked at ${releases.length} release(s) of ${REPO}.`,
          'Releases from before the standalone executables existed carry only the npm package.',
        )
      }

      const { manifest: manifestAsset, archive: archiveAsset } = binaryAssets(release, decision.target)
      intended = versionOf(release)
      say(`Installing LoopTroop ${intended} (${decision.target}) into ${prefix}`)

      // No `checkRuntime` here, deliberately. The floor a release records is the
      // Node it needs to *run*, and this executable carries its own — so
      // enforcing it would refuse to install, on the grounds of a missing Node,
      // the one build that does not need one.
      const manifestPath = resolve(workDir, MANIFEST_ASSET)
      await download(manifestAsset.browser_download_url, manifestPath)
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))

      const digest = manifest.assets?.[archiveAsset.name]
      if (!digest) {
        fail(
          `The release manifest for ${intended} records no checksum for ${archiveAsset.name}.`,
          'Installing it would mean trusting a download with nothing to check it against.',
        )
      }

      const archivePath = resolve(workDir, archiveAsset.name)
      if (options.dryRun) {
        say(`would download ${archiveAsset.browser_download_url}`)
        say(`would verify sha256 ${digest.sha256}`)
        say(`would install ${archiveAsset.name} into ${join(prefix, 'bin')}`)
        return
      }

      say(`Downloading ${archiveAsset.name}...`)
      await download(archiveAsset.browser_download_url, archivePath)
      verifyBytes(archivePath, digest)

      // The daemon, if there was one, is already back up: `installBinary`
      // restarts it before letting go of the backup, so that a daemon which
      // will not start is a rollback rather than an outage.
      const { installed, wasRunning } = installBinary(archivePath, { version: intended, prefix })
      installedPath = installed
      say(`Installed ${installed}${wasRunning ? ', and the daemon is running again' : ''}`)

      const bin = join(prefix, 'bin')
      pathAdvice = onPath(bin)
        ? [`It is installed at ${installed}, and ${bin} is already on your PATH.`]
        : process.platform === 'win32'
          ? [
            `Add ${bin} to your PATH, then open a new terminal:`,
            `  [Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path', 'User') + ';${bin}', 'User')`,
          ]
          : [
            `Add ${bin} to your PATH, then open a new terminal:`,
            `  echo 'export PATH="${bin}:$PATH"' >> ~/.profile`,
          ]
    } else if (options.tarball !== null) {
      const local = resolve(options.tarball)
      if (!statSync(local, { throwIfNoEntry: false })?.isFile()) fail(`No such tarball: ${local}`)
      say(`Installing from ${local} (local file: no checksum to compare against).`)
      if (options.dryRun) return say(`would install ${local}`)
      installGlobally(local)
    } else {
      // 100 is the API's maximum page size, and this deliberately reads one
      // page rather than paginating. The endpoint returns newest first and the
      // answer is normally the first entry, so paging further would only matter
      // if the hundred most recent releases in a row carried no installable
      // assets — which would mean something far more wrong than a lookup.
      //
      // The failure is loud either way: an unfound release is an error naming
      // how many were examined, never a quiet fallback to something older.
      const url = options.version === null
        ? `${API}/repos/${REPO}/releases?per_page=100`
        : `${API}/repos/${REPO}/releases/tags/v${options.version}`
      const payload = await getJson(url)
      const releases = Array.isArray(payload) ? payload : [payload]

      const release = selectRelease(releases, options.version)
      if (release === null) {
        fail(
          options.version === null
            ? 'No published release carries installable assets yet.'
            : `Release v${options.version} has no installable assets.`,
          `Looked at ${releases.length} release(s) of ${REPO}.`,
        )
      }

      const { manifest: manifestAsset, tarball: tarballAsset } = installableAssets(release)
      intended = versionOf(release)
      say(`Installing LoopTroop ${intended}`)

      const manifestPath = resolve(workDir, MANIFEST_ASSET)
      await download(manifestAsset.browser_download_url, manifestPath)
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))

      checkRuntime(manifest.engines)

      const tarballPath = resolve(workDir, tarballAsset.name)
      if (options.dryRun) {
        say(`would download ${tarballAsset.browser_download_url}`)
        say(`would verify sha256 ${manifest.sha256}`)
        say(`would install ${tarballAsset.name}`)
        return
      }

      say(`Downloading ${tarballAsset.name}...`)
      await download(tarballAsset.browser_download_url, tarballPath)
      verifyBytes(tarballPath, manifest)
      installGlobally(tarballPath)
    }
  } finally {
    // Through `discard`, which retries and never throws. Failing to remove a
    // temporary directory must not turn an install that worked into one that
    // reports an error — and on Windows, after unpacking and running an
    // executable, that is a real possibility rather than a theoretical one.
    discard(workDir)
  }

  // Advisory only. `doctor` exits non-zero until OpenCode is set up, which is
  // the normal state seconds after installing, so a failing check here would
  // report a broken install that is not broken.
  //
  // This runs the bare command, deliberately: the question it answers is what
  // the user's shell will do when they type `looptroop`, not whether files
  // landed on disk. But that means the answer can come from a different copy
  // earlier in PATH, so it is checked against what was actually installed
  // rather than reported as though it must be the same thing. Reporting it
  // blindly claimed a successful install of whatever version happened to
  // answer — including, when npm's global bin is not on PATH at all, an older
  // copy that the install never touched.
  const probe = runTool('looptroop', ['--version'], { encoding: 'utf8' })
  const reported = probe.status === 0 ? String(probe.stdout).trim() : null
  say('')
  if (reported === null) {
    say('Installed, but `looptroop` is not on your PATH yet.')
    for (const line of pathAdvice) say(line)
  } else if (intended === null || reported === intended) {
    say(`Installed: looptroop ${reported}`)
  } else {
    say(`Installed: looptroop ${intended}`)
    say('')
    say(`But \`looptroop\` on your PATH is ${reported}, so another copy comes first.`)
    if (installedPath !== null) say(`This install is at ${installedPath}.`)
    say(`Find it with: ${process.platform === 'win32' ? 'where looptroop' : 'command -v looptroop'}`)
  }
  say('')
  // `open` rather than `setup`: LoopTroop is used through its interface, and
  // `open` starts the daemon itself and lands the user in it. `setup` attaches a
  // project from the terminal, which is a thing you may never need to do.
  say('Next: run `looptroop doctor` to check this machine, then `looptroop open`.')
}

/**
 * Is this file the program being run, rather than something imported?
 *
 * Through `realpath` on both sides, which is not pedantry. The wrappers write
 * this file into the system temporary directory and run it from there, and on
 * macOS that directory is reached through `/var`, a symlink to `/private/var`.
 * Node resolves symlinks when it records `import.meta.url` and does not when it
 * records `argv[1]`, so a naive comparison is false on exactly one platform —
 * and a false answer here is not an error, it is a program that does nothing at
 * all and exits 0. The installer "succeeded" and installed nothing.
 */
function isMainModule() {
  const invoked = process.argv[1]
  if (invoked === undefined) return false
  try {
    return realpathSync(fileURLToPath(import.meta.url)) === realpathSync(invoked)
  } catch {
    // Either path may not exist under an unusual loader; fall back to comparing
    // them unresolved rather than refusing to run.
    return import.meta.url === pathToFileURL(invoked).href
  }
}

if (isMainModule()) {
  try {
    await main(process.argv.slice(2))
  } catch (error) {
    if (!(error instanceof InstallError)) throw error
    process.stderr.write(`\nlooptroop install: ${error.message}\n`)
    for (const line of error.detail) process.stderr.write(`  ${line}\n`)
    process.stderr.write('\n')
    // Not `process.exit`: see InstallError. The process ends once the last
    // handle closes, which for a finished fetch is immediately.
    process.exitCode = 1
  }
}
LOOPTROOP_INSTALLER_CORE
# --- END installer-core ---

# A heredoc that got truncated leaves an empty file, and `node` on an empty file
# exits 0 without doing anything — an installer that reports success and
# installs nothing. Cheap to check, and the failure it catches is silent.
if [ ! -s "$core" ]; then
  echo "LoopTroop installer: the installer was truncated in transit; nothing was installed." >&2
  echo "Download it and run it from a file: https://www.looptroop.ovh/install" >&2
  exit 1
fi

# Not `exec`, which is what this used to be. `exec` replaces this shell with
# node, so the EXIT trap above never runs and every install — successful or not
# — left its temporary directory behind.
#
# What `exec` gave has to be reproduced by hand, because it is not nothing:
#
#   - Signal delivery. A backgrounded child stays in this shell's process group,
#     so Ctrl+C at a terminal still reaches it directly. What it does not cover
#     is a signal sent to this script's pid alone, which `timeout` and most
#     supervisors do, so those three are forwarded.
#   - The exit status, including the 128+signal form a killed child reports.
#     `wait` returns that same shape when *this shell* is interrupted before the
#     child has finished reacting, so it is waited on again until the child is
#     genuinely gone; the status is the child's either way.
#
# The one thing that changes is the child's standard input, which for an
# asynchronous command in a non-interactive shell is /dev/null. Nothing in the
# install reads stdin, and what it inherited before was the remainder of the
# `curl … | sh` pipe, which was never useful to it.
node "$core" "$@" &
child=$!

forward() {
  kill -"$1" "$child" 2>/dev/null || true
}
trap 'forward INT' INT
trap 'forward TERM' TERM
trap 'forward HUP' HUP

status=0
while :; do
  status=0
  wait "$child" || status=$?
  if [ "$status" -gt 128 ] && kill -0 "$child" 2>/dev/null; then
    continue
  fi
  break
done

exit "$status"
