#!/bin/sh
# LoopTroop installer for macOS and Linux.
#
#   curl -fsSL https://www.looptroop.ovh/install | sh
#   curl -fsSL https://www.looptroop.ovh/install | sh -s -- --version 9.9.9
#
# Downloads the tarball a LoopTroop release published, checks it against the
# checksum that release recorded, and installs it with npm. It never installs
# Node, never asks for sudo, and never writes outside npm's global prefix.
#
# All of the actual work is in `scripts/installer-core.mjs`, copied verbatim
# into the block at the bottom of this file. Node is required to install
# LoopTroop at all, so doing the JSON, HTTPS, semver and hashing there rather
# than here means one implementation instead of one per shell, and no dependency
# on curl, jq or shasum being present and identical on every platform.
set -eu

node_missing() {
  echo "LoopTroop needs Node.js (24 LTS or newer) and it is not on your PATH." >&2
  echo "" >&2
  case "$(uname -s 2>/dev/null || echo unknown)" in
    Darwin) echo "  brew install node@24" >&2 ;;
    Linux)  echo "  Use your distribution's package, or https://github.com/nvm-sh/nvm" >&2 ;;
    *)      echo "  https://nodejs.org/" >&2 ;;
  esac
  echo "  ...or download an installer from https://nodejs.org/" >&2
  echo "" >&2
  echo "Then run this installer again. It will not install Node for you." >&2
  exit 1
}

command -v node >/dev/null 2>&1 || node_missing

work=$(mktemp -d 2>/dev/null || mktemp -d -t looptroop-install)
# `sh` has no scoped cleanup, and leaving the core behind in a world-readable
# temp directory is untidy rather than dangerous, but it is still litter.
trap 'rm -rf "$work"' EXIT INT TERM
core="$work/installer-core.mjs"

# --- BEGIN installer-core (generated by scripts/sync-installers.mjs; do not edit) ---
cat > "$core" <<'LOOPTROOP_INSTALLER_CORE'
#!/usr/bin/env node
/**
 * Installs LoopTroop from a GitHub release, verifying the bytes first.
 *
 *   node installer-core.mjs [--version X.Y.Z] [--tarball PATH] [--dry-run]
 *
 * This is the whole installer. `install.sh` and `install.ps1` are wrappers that
 * find Node, write this file to a temporary directory and run it — everything
 * that could get a decision wrong lives here, once, where it can be tested,
 * rather than twice in two shell dialects. `scripts/sync-installers.mjs`
 * copies this file into both wrappers and CI fails if a copy has drifted.
 *
 * Node is a hard prerequisite either way, so using it for JSON, semver, HTTPS
 * and hashing costs nothing and avoids depending on curl, jq, shasum or
 * certutil being present and behaving the same on three platforms.
 *
 * What it installs is an npm tarball, installed with npm (D2a): `npm uninstall
 * -g looptroop` and `npm install -g looptroop@latest` keep working afterwards,
 * which would not be true of an installer that unpacked files itself.
 */
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdtempSync, readFileSync, realpathSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const REPO = process.env.LOOPTROOP_INSTALL_REPO || 'looptroop-ai/LoopTroop'
// Overridable so the tests can serve a fixture release index from localhost.
const API = process.env.LOOPTROOP_INSTALL_API || 'https://api.github.com'
const MANIFEST_ASSET = 'release-manifest.json'
const TARBALL_PATTERN = /^looptroop-.+\.tgz$/

const NODE_HELP = {
  darwin: 'brew install node@24   (or download from https://nodejs.org/)',
  win32: 'winget install OpenJS.NodeJS.LTS   (or download from https://nodejs.org/)',
  linux: 'Use your distribution\'s package or https://github.com/nvm-sh/nvm',
}

/**
 * Refuses to go on, and says why.
 *
 * Thrown rather than `process.exit`ed. Calling `process.exit()` while a fetch
 * connection is still open crashes Node on Windows with 0xC0000409 instead of
 * exiting 1 — so a user who gave a bad checksum, or an old Node, saw a crash
 * where a message belonged. Unwinding to the top and letting the process end on
 * its own gets the message out and the exit code right on every platform.
 */
class InstallError extends Error {
  constructor(message, detail) {
    super(message)
    this.name = 'InstallError'
    this.detail = detail
  }
}

function fail(message, ...detail) {
  throw new InstallError(message, detail.filter(Boolean))
}

function say(message) {
  process.stdout.write(`${message}\n`)
}

// --- pure decisions -------------------------------------------------------

export function parseArgs(argv) {
  const options = { version: null, tarball: null, dryRun: false }

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    const takeValue = () => {
      const value = argv[index + 1]
      if (value === undefined || value.startsWith('--')) fail(`${arg} needs a value.`)
      index += 1
      return value
    }

    switch (arg) {
      case '--version': options.version = takeValue().replace(/^v/, ''); break
      case '--tarball': options.tarball = takeValue(); break
      case '--dry-run': options.dryRun = true; break
      case '--help':
      case '-h':
        say('Usage: install.sh [--version X.Y.Z] [--tarball PATH]')
        say('')
        say('  --version X.Y.Z  install exactly this release, prereleases included')
        say('  --tarball PATH   install an already-downloaded tarball, skipping the network')
        process.exit(0)
        break
      default:
        fail(`Unknown option ${arg}.`, 'Run with --help to see what is accepted.')
    }
  }

  return options
}

/**
 * Semver ordering, prereleases below the release they precede.
 *
 * Only what release tags actually use: numeric core plus a dot-separated
 * prerelease, compared numerically where both parts are numeric and
 * lexically otherwise, as the spec requires.
 */
export function compareVersions(left, right) {
  const split = (value) => {
    const [core, pre = null] = String(value).replace(/^v/, '').split('-', 2)
    return { core: core.split('.').map((part) => Number.parseInt(part, 10) || 0), pre }
  }

  const a = split(left)
  const b = split(right)

  for (let index = 0; index < Math.max(a.core.length, b.core.length); index += 1) {
    const difference = (a.core[index] ?? 0) - (b.core[index] ?? 0)
    if (difference !== 0) return difference < 0 ? -1 : 1
  }

  if (a.pre === b.pre) return 0
  if (a.pre === null) return 1
  if (b.pre === null) return -1

  const aParts = a.pre.split('.')
  const bParts = b.pre.split('.')
  for (let index = 0; index < Math.max(aParts.length, bParts.length); index += 1) {
    const x = aParts[index]
    const y = bParts[index]
    if (x === y) continue
    if (x === undefined) return -1
    if (y === undefined) return 1
    const numeric = /^\d+$/.test(x) && /^\d+$/.test(y)
    if (numeric) return Number(x) - Number(y) < 0 ? -1 : 1
    return x < y ? -1 : 1
  }

  return 0
}

export function versionOf(release) {
  return String(release.tag_name ?? '').replace(/^v/, '')
}

/** The assets an install needs; a release without both is not installable. */
export function installableAssets(release) {
  const assets = Array.isArray(release.assets) ? release.assets : []
  const manifest = assets.find((asset) => asset.name === MANIFEST_ASSET)
  const tarball = assets.find((asset) => TARBALL_PATTERN.test(String(asset.name)))
  return manifest && tarball ? { manifest, tarball } : null
}

/**
 * The release to install: the pinned one, or the newest stable that can
 * actually be installed.
 *
 * "That can actually be installed" is not pedantry. An early release was
 * published with no assets at all, so a walk that stopped at the newest stable
 * tag would resolve to a release with nothing to download — and would do so
 * again for any future release whose asset upload failed halfway.
 */
export function selectRelease(releases, pinned = null) {
  const candidates = releases
    .filter((release) => release && release.draft !== true)
    .filter((release) => (pinned === null ? release.prerelease !== true : versionOf(release) === pinned))
    .filter((release) => installableAssets(release) !== null)

  candidates.sort((a, b) => compareVersions(versionOf(b), versionOf(a)))
  return candidates[0] ?? null
}

/** True when `have` satisfies a `>=x.y.z` style floor. */
export function satisfiesFloor(have, floor) {
  const minimum = String(floor).replace(/^[^\d]*/, '')
  return minimum === '' || compareVersions(have, minimum) >= 0
}

// --- effects --------------------------------------------------------------

async function getJson(url) {
  const headers = { accept: 'application/vnd.github+json', 'user-agent': 'looptroop-installer' }
  // Only to lift the 60-per-hour anonymous rate limit when one happens to be
  // present, as in CI. Never required, never printed.
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN
  if (token) headers.authorization = `Bearer ${token}`

  let response
  try {
    response = await fetch(url, { headers })
  } catch (error) {
    fail('Could not reach GitHub.', String(error.message ?? error), 'Check your network and try again.')
  }
  if (!response.ok) {
    fail(
      `GitHub answered ${response.status} for the release list.`,
      response.status === 403 ? 'That is usually the anonymous rate limit; try again in a few minutes.' : '',
    )
  }
  return response.json()
}

async function download(url, destination) {
  const response = await fetch(url, { headers: { 'user-agent': 'looptroop-installer' }, redirect: 'follow' })
  if (!response.ok) fail(`Downloading ${basename(destination)} failed with ${response.status}.`)
  writeFileSync(destination, Buffer.from(await response.arrayBuffer()))
}

function npmVersion() {
  const probe = spawnSync('npm', ['--version'], { encoding: 'utf8', shell: process.platform === 'win32' })
  return probe.status === 0 ? String(probe.stdout).trim() : null
}

/**
 * Checked against the floor the release itself records, not one baked in here:
 * an installer that hardcodes the requirement is wrong for every release but
 * the one it shipped with. Manifests written before `engines` existed simply
 * carry no floor, and are not treated as failing one.
 */
function checkRuntime(engines) {
  if (!engines) return

  if (engines.node && !satisfiesFloor(process.versions.node, engines.node)) {
    fail(
      `LoopTroop needs Node ${engines.node}; this is ${process.versions.node}.`,
      NODE_HELP[process.platform] ?? NODE_HELP.linux,
      'LoopTroop will not install Node for you.',
    )
  }

  const npm = npmVersion()
  if (npm === null) fail('npm is not on PATH, and installing needs it.', 'It ships with Node; reinstall Node.')
  if (engines.npm && !satisfiesFloor(npm, engines.npm)) {
    fail(`LoopTroop needs npm ${engines.npm}; this is ${npm}.`, `Upgrade with: npm install -g npm@${engines.npm.replace(/^[^\d]*/, '')}`)
  }
}

function verifyBytes(file, manifest) {
  const bytes = readFileSync(file)
  const sha256 = createHash('sha256').update(bytes).digest('hex')

  if (typeof manifest.bytes === 'number' && bytes.length !== manifest.bytes) {
    fail(`${basename(file)} is ${bytes.length} bytes; the release records ${manifest.bytes}.`, 'Nothing was installed.')
  }
  if (sha256 !== manifest.sha256) {
    fail(
      `${basename(file)} does not match the checksum this release published.`,
      `computed ${sha256}`,
      `expected ${manifest.sha256}`,
      'Nothing was installed.',
    )
  }

  say(`Verified sha256 ${sha256}`)
}

function installGlobally(tarball) {
  say(`Installing with npm...`)
  const result = spawnSync('npm', ['install', '-g', tarball, '--no-audit', '--no-fund'], {
    stdio: 'inherit',
    shell: process.platform === 'win32',
  })

  if (result.status !== 0) {
    fail(
      'npm could not install LoopTroop globally.',
      'If that was a permissions error, point npm at a directory you own rather than using sudo:',
      '  npm config set prefix ~/.npm-global',
      '  export PATH="$HOME/.npm-global/bin:$PATH"',
    )
  }
}

async function main(argv) {
  const options = parseArgs(argv)
  const workDir = mkdtempSync(resolve(tmpdir(), 'looptroop-install-'))

  try {
    if (options.tarball !== null) {
      const local = resolve(options.tarball)
      if (!statSync(local, { throwIfNoEntry: false })?.isFile()) fail(`No such tarball: ${local}`)
      say(`Installing from ${local} (local file: no checksum to compare against).`)
      if (options.dryRun) return say(`would install ${local}`)
      installGlobally(local)
    } else {
      // 100 is the API's maximum page size, and this deliberately reads one
      // page rather than paginating. The endpoint returns newest first and the
      // answer is normally the first entry, so paging further would only matter
      // if the hundred most recent releases in a row carried no installable
      // assets — which would mean something far more wrong than a lookup.
      //
      // The failure is loud either way: an unfound release is an error naming
      // how many were examined, never a quiet fallback to something older.
      const url = options.version === null
        ? `${API}/repos/${REPO}/releases?per_page=100`
        : `${API}/repos/${REPO}/releases/tags/v${options.version}`
      const payload = await getJson(url)
      const releases = Array.isArray(payload) ? payload : [payload]

      const release = selectRelease(releases, options.version)
      if (release === null) {
        fail(
          options.version === null
            ? 'No published release carries installable assets yet.'
            : `Release v${options.version} has no installable assets.`,
          `Looked at ${releases.length} release(s) of ${REPO}.`,
        )
      }

      const { manifest: manifestAsset, tarball: tarballAsset } = installableAssets(release)
      say(`Installing LoopTroop ${versionOf(release)}`)

      const manifestPath = resolve(workDir, MANIFEST_ASSET)
      await download(manifestAsset.browser_download_url, manifestPath)
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))

      checkRuntime(manifest.engines)

      const tarballPath = resolve(workDir, tarballAsset.name)
      if (options.dryRun) {
        say(`would download ${tarballAsset.browser_download_url}`)
        say(`would verify sha256 ${manifest.sha256}`)
        say(`would install ${tarballAsset.name}`)
        return
      }

      say(`Downloading ${tarballAsset.name}...`)
      await download(tarballAsset.browser_download_url, tarballPath)
      verifyBytes(tarballPath, manifest)
      installGlobally(tarballPath)
    }
  } finally {
    rmSync(workDir, { recursive: true, force: true })
  }

  // Advisory only. `doctor` exits non-zero until OpenCode is set up, which is
  // the normal state seconds after installing, so a failing check here would
  // report a broken install that is not broken.
  const probe = spawnSync('looptroop', ['--version'], { encoding: 'utf8', shell: process.platform === 'win32' })
  say('')
  if (probe.status === 0) {
    say(`Installed: looptroop ${String(probe.stdout).trim()}`)
  } else {
    say('Installed, but `looptroop` is not on your PATH yet.')
    say('Open a new terminal, or add npm\'s global bin directory to PATH: npm prefix -g')
  }
  say('')
  say('Next: run `looptroop doctor` to check your setup, then `looptroop setup`.')
}

/**
 * Is this file the program being run, rather than something imported?
 *
 * Through `realpath` on both sides, which is not pedantry. The wrappers write
 * this file into the system temporary directory and run it from there, and on
 * macOS that directory is reached through `/var`, a symlink to `/private/var`.
 * Node resolves symlinks when it records `import.meta.url` and does not when it
 * records `argv[1]`, so a naive comparison is false on exactly one platform —
 * and a false answer here is not an error, it is a program that does nothing at
 * all and exits 0. The installer "succeeded" and installed nothing.
 */
function isMainModule() {
  const invoked = process.argv[1]
  if (invoked === undefined) return false
  try {
    return realpathSync(fileURLToPath(import.meta.url)) === realpathSync(invoked)
  } catch {
    // Either path may not exist under an unusual loader; fall back to comparing
    // them unresolved rather than refusing to run.
    return import.meta.url === pathToFileURL(invoked).href
  }
}

if (isMainModule()) {
  try {
    await main(process.argv.slice(2))
  } catch (error) {
    if (!(error instanceof InstallError)) throw error
    process.stderr.write(`\nlooptroop install: ${error.message}\n`)
    for (const line of error.detail) process.stderr.write(`  ${line}\n`)
    process.stderr.write('\n')
    // Not `process.exit`: see InstallError. The process ends once the last
    // handle closes, which for a finished fetch is immediately.
    process.exitCode = 1
  }
}
LOOPTROOP_INSTALLER_CORE
# --- END installer-core ---

# A heredoc that got truncated leaves an empty file, and `node` on an empty file
# exits 0 without doing anything — an installer that reports success and
# installs nothing. Cheap to check, and the failure it catches is silent.
if [ ! -s "$core" ]; then
  echo "LoopTroop installer: the installer was truncated in transit; nothing was installed." >&2
  echo "Download it and run it from a file: https://www.looptroop.ovh/install" >&2
  exit 1
fi

exec node "$core" "$@"
