#!/usr/bin/env node
'use strict'

// Deliberately ES5, CommonJS, and dependency-free. This file is parsed by
// whatever Node the user happens to have, so any modern syntax here would
// produce a SyntaxError instead of the friendly message below — which is also
// why the floor is three literals here rather than an import of the module
// everything else reads. They are written by `scripts/sync-installers.mjs`
// from `engines.node`; `npm run installers:check` fails if they drift.

// --- BEGIN node-floor (generated by scripts/sync-installers.mjs; do not edit) ---
var REQUIRED_MAJOR = 24
var REQUIRED_MINOR = 18
var REQUIRED_PATCH = 1
// --- END node-floor ---
var REQUIRED_LABEL = REQUIRED_MAJOR + '.' + REQUIRED_MINOR + '.' + REQUIRED_PATCH

function parseVersion(raw) {
  var text = String(raw)
  var parts = text.split('-')[0].split('.')
  return {
    major: parseInt(parts[0], 10) || 0,
    minor: parseInt(parts[1], 10) || 0,
    patch: parseInt(parts[2], 10) || 0,
    prerelease: text.indexOf('-') !== -1
  }
}

// Patch-level, because the floor is a patch release. A major.minor comparison
// refused 24.18.0 while printing 24.18.0 as the version to install.
//
// A prerelease of the floor is below it, which is how npm reads `engines.node`
// and what `scripts/installer-core.mjs` already does: 24.18.1-nightly.0 comes
// before 24.18.1 and does not carry its fixes.
function isSupported(raw) {
  var version = parseVersion(raw)
  if (version.major !== REQUIRED_MAJOR) return version.major > REQUIRED_MAJOR
  if (version.minor !== REQUIRED_MINOR) return version.minor > REQUIRED_MINOR
  if (version.patch !== REQUIRED_PATCH) return version.patch > REQUIRED_PATCH
  return !version.prerelease
}

// Platform-neutral: nvm is not how anybody installs Node on Windows, and this
// message is printed on whatever machine the user happens to be on.
function nodeHelp() {
  if (process.platform === 'darwin') return '  brew install node@' + REQUIRED_MAJOR + '\n'
  if (process.platform === 'win32') return '  winget install OpenJS.NodeJS.LTS\n'
  return '  Use your distribution\'s package or https://github.com/nvm-sh/nvm\n'
}

if (!isSupported(process.versions.node)) {
  process.stderr.write(
    'LoopTroop requires Node.js ' + REQUIRED_LABEL + ' or newer.\n' +
    'You are running Node.js ' + process.versions.node + '.\n\n' +
    'Install a supported version:\n' +
    nodeHelp() +
    '  ...or download an installer from https://nodejs.org/\n'
  )
  process.exit(1)
}

// Only reached on a supported runtime, so the real CLI is free to use modern
// syntax and ES modules.
import('./cli.js').then(function (cli) {
  return cli.main(process.argv.slice(2))
}).then(function (code) {
  process.exitCode = code
}).catch(function (error) {
  process.stderr.write('LoopTroop failed to start: ' + (error && error.message ? error.message : error) + '\n')
  process.exitCode = 1
})
