import { AsyncLocalStorage } from 'node:async_hooks'
import { contentSha256 } from '../lib/contentHash'
import { LOG_TRUNCATION_LENGTH } from '../lib/constants'
import type { WorkflowPhaseId } from '@shared/workflowMeta'

interface CommandLogContext {
  ticketId: string
  externalId: string
  phase: WorkflowPhaseId
  fields?: Record<string, unknown>
  state: {
    isEmittingCommandLog: boolean
    lastCommandLogHash: string
    lastCommandLogTimestamp: number
  }
  /** Emitter callback for SYS log entries. */
  emit: (phase: WorkflowPhaseId, type: 'info' | 'error', content: string, data?: Record<string, unknown>) => void
}

// Use a globalThis singleton so the same AsyncLocalStorage is shared across
// ESM (import) and CJS (require) module instances. Without this, the project's
// "type": "module" setting causes require() in logCmd() wrappers to load a
// separate module instance whose commandLogStore is a different object —
// making logCommand() always see undefined context and silently no-op.
const STORE_KEY = Symbol.for('looptroop:commandLogStore')
type GlobalCommandLogStore = typeof globalThis & {
  [key: symbol]: AsyncLocalStorage<CommandLogContext> | undefined
}

function getSharedStore(): AsyncLocalStorage<CommandLogContext> {
  const g = globalThis as GlobalCommandLogStore
  if (!g[STORE_KEY]) {
    g[STORE_KEY] = new AsyncLocalStorage<CommandLogContext>()
  }
  return g[STORE_KEY]!
}
const commandLogStore = getSharedStore()

/** Current command-logging context, or undefined outside a withCommandLogging scope. */
export function getCommandLogContext(): CommandLogContext | undefined {
  return commandLogStore.getStore()
}

type LoggedCommandResult =
  | { ok: true; stdin?: string; stdout?: string; stderr?: string }
  | { ok: false; error: string; stdin?: string; stdout?: string; stderr?: string }

/**
 * Run `fn` with command-logging context active.  Any `logCommand()` calls
 * made anywhere in the call stack inside `fn` will emit SYS log entries
 * for the given ticket/phase via the provided `emit` function.
 */
export function withCommandLogging<T>(
  ticketId: string,
  externalId: string,
  phase: WorkflowPhaseId,
  fn: () => T,
  emit: CommandLogContext['emit'],
): T {
  return commandLogStore.run({
    ticketId,
    externalId,
    phase,
    emit,
    state: { isEmittingCommandLog: false, lastCommandLogHash: '', lastCommandLogTimestamp: 0 },
  }, fn)
}

/**
 * Async variant of `withCommandLogging` for async callers.
 */
export async function withCommandLoggingAsync<T>(
  ticketId: string,
  externalId: string,
  phase: WorkflowPhaseId,
  fn: () => Promise<T>,
  emit: CommandLogContext['emit'],
): Promise<T> {
  return commandLogStore.run({
    ticketId,
    externalId,
    phase,
    emit,
    state: { isEmittingCommandLog: false, lastCommandLogHash: '', lastCommandLogTimestamp: 0 },
  }, fn)
}

// Dedup window: suppress identical command log lines emitted within this interval
const CMD_LOG_DEDUP_WINDOW_MS = 1000
const COMMAND_LOG_OUTPUT_PREVIEW_LENGTH = 2500

function hashCommandContent(content: string): string {
  return contentSha256(content)
}

function emitCommandLog(
  ctx: CommandLogContext,
  type: 'info' | 'error',
  content: string,
) {
  // Persisting a command log can trigger git/path lookups; suppress any
  // nested command logging generated by that persistence path.
  if (ctx.state.isEmittingCommandLog) return

  // Skip exact-duplicate log lines within the dedup window
  const now = Date.now()
  const contentHash = hashCommandContent(content)
  if (
    contentHash === ctx.state.lastCommandLogHash
    && now - ctx.state.lastCommandLogTimestamp < CMD_LOG_DEDUP_WINDOW_MS
  ) {
    return
  }
  ctx.state.lastCommandLogHash = contentHash
  ctx.state.lastCommandLogTimestamp = now

  ctx.state.isEmittingCommandLog = true
  try {
    ctx.emit(ctx.phase, type, content, ctx.fields)
  } finally {
    ctx.state.isEmittingCommandLog = false
  }
}

export async function withCommandLoggingFieldsAsync<T>(
  fields: Record<string, unknown>,
  fn: () => Promise<T>,
): Promise<T> {
  const ctx = commandLogStore.getStore()
  if (!ctx) return await fn()
  return await commandLogStore.run({
    ...ctx,
    fields: {
      ...(ctx.fields ?? {}),
      ...fields,
    },
  }, fn)
}

/**
 * Log a shell command execution result as a SYS log entry.
 * No-op if no command-logging context is active.
 *
 * @param bin     The binary name (e.g. 'git')
 * @param args    The arguments array
 * @param result  The outcome: `{ ok: true, stdout? }` or `{ ok: false, error }`
 */
export function logCommand(
  bin: string,
  args: string[],
  result: LoggedCommandResult,
) {
  const ctx = commandLogStore.getStore()
  if (!ctx) return

  // Build a human-readable command string, redacting the -C <path> for brevity
  const displayArgs = redactCwd(args)
  const cmdStr = `${bin} ${displayArgs.join(' ')}`
  const commandText = [bin, ...args].join(' ')

  let content: string
  let type: 'info' | 'error'

  const shouldUseStructuredOutput = shouldRenderStructuredCommandOutput(result)

  if (result.ok) {
    const pushLog = formatKnownGitPushLog(bin, args, cmdStr, result)
    if (pushLog !== null) {
      emitCommandLog(ctx, 'info', pushLog)
      return
    }

    const probeOutcome = shouldUseStructuredOutput
      ? null
      : formatKnownGitProbeSuccess(commandText, result.stdout, result.stderr)
    if (probeOutcome) {
      content = `[CMD] $ ${cmdStr}  →  ${truncateOutput(probeOutcome, COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`
      type = 'info'
      emitCommandLog(ctx, type, content)
      return
    }

    if (shouldUseStructuredOutput) {
      content = formatStructuredCommandLog(cmdStr, result)
    } else {
      const outputStr = formatCompactCommandOutput(result.stdout, result.stderr)
      const silentOutcome = outputStr ? null : formatKnownSilentSuccess(bin, args)
      content = `[CMD] $ ${cmdStr}  →  ${truncateOutput(outputStr || silentOutcome || 'ok', COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`
    }
    type = 'info'
  } else {
    const benignProbeFailure = shouldUseStructuredOutput
      ? null
      : formatKnownGitProbeFailure(commandText, result.error)
    if (benignProbeFailure) {
      content = `[CMD] $ ${cmdStr}  →  ${truncateOutput(benignProbeFailure, COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`
      type = 'info'
      emitCommandLog(ctx, type, content)
      return
    }

    if (shouldUseStructuredOutput) {
      content = formatStructuredCommandLog(cmdStr, result)
    } else {
      const error = compactCommandText(result.error)
      content = `[CMD] $ ${cmdStr}  →  error: ${truncateOutput(error, COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`
    }
    type = 'error'
  }

  emitCommandLog(ctx, type, content)
}

/**
 * Redact the `-C <path>` git flag to keep logs concise.
 * Shows just the last two path segments instead of the full absolute path.
 */
function redactCwd(args: string[]): string[] {
  const result: string[] = []
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '-C' && i + 1 < args.length) {
      const fullPath = args[i + 1]!
      const shortPath = fullPath.split('/').slice(-2).join('/')
      result.push('-C', shortPath)
      i++ // skip the path argument
    } else {
      result.push(args[i]!)
    }
  }
  return result
}

function compactCommandText(text: string | undefined): string {
  return normalizeCommandText(text).replace(/\n+/g, ' | ')
}

function normalizeCommandText(text: string | undefined): string {
  return (text ?? '')
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .replace(/\0+/g, '\n')
    .trim()
}

function formatCompactCommandOutput(stdout?: string, stderr?: string): string {
  const normalizedStdout = compactCommandText(stdout)
  const normalizedStderr = compactCommandText(stderr)

  if (normalizedStdout && normalizedStderr) {
    return `STDOUT: ${normalizedStdout} | STDERR: ${normalizedStderr}`
  }
  if (normalizedStdout) return normalizedStdout
  if (normalizedStderr) return `STDERR: ${normalizedStderr}`
  return ''
}

function shouldRenderStructuredCommandOutput(result: LoggedCommandResult): boolean {
  const stdin = normalizeCommandText(result.stdin)
  const stdout = normalizeCommandText(result.stdout)
  const stderr = normalizeCommandText(result.stderr)

  if (stdin) return true
  if (!result.ok && (stdout || stderr)) return true
  if (stderr) return true
  if (stdout.includes('\n')) return true
  return false
}

function formatStructuredCommandLog(cmdStr: string, result: LoggedCommandResult): string {
  const sections: string[] = []
  const stdin = normalizeCommandText(result.stdin)
  const stdout = normalizeCommandText(result.stdout)
  const stderr = normalizeCommandText(result.stderr)

  if (stdin) {
    sections.push(`STDIN:\n${truncateOutput(stdin, COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`)
  }

  if (!result.ok) {
    const detail = normalizeCommandText(result.error)
    if (shouldIncludeErrorSection(detail, stdout, stderr)) {
      sections.push(`ERROR:\n${truncateOutput(detail, COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`)
    }
  }

  if (stdout) {
    sections.push(`STDOUT:\n${truncateOutput(stdout, COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`)
  }

  if (stderr) {
    sections.push(`STDERR:\n${truncateOutput(stderr, COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`)
  }

  return [`[CMD] $ ${cmdStr}`, ...sections].join('\n')
}

function shouldIncludeErrorSection(detail: string, stdout: string, stderr: string): boolean {
  if (!detail) return false
  if (detail === stdout || detail === stderr) return false
  return true
}

function isLikelyBenignGitProbeFailure(error: string): boolean {
  const normalized = error.trim()
  return normalized === 'exit code 1' || normalized === 'command returned non-zero'
}

/**
 * Formats a successful git push log entry with a compact summary header and
 * the remote output (git's STDERR) labeled as REMOTE: to distinguish it from
 * actual errors. Returns null when there is no output (silent path handles it).
 */
function formatKnownGitPushLog(
  bin: string,
  args: string[],
  cmdStr: string,
  result: LoggedCommandResult,
): string | null {
  if (!result.ok || result.stdin) return null
  if (bin !== 'git') return null

  const command = getGitSubcommand(args)
  if (command?.name !== 'push') return null

  const stderr = normalizeCommandText(result.stderr)
  const stdout = normalizeCommandText(result.stdout)

  // No output — fall through to the silent path which returns 'push completed'
  if (!stderr && !stdout) return null

  const sections: string[] = [`[CMD] $ ${cmdStr}  →  push completed`]

  if (stdout) {
    sections.push(`STDOUT:\n${truncateOutput(stdout, COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`)
  }
  if (stderr) {
    sections.push(`REMOTE:\n${truncateOutput(stderr, COMMAND_LOG_OUTPUT_PREVIEW_LENGTH)}`)
  }

  return sections.join('\n')
}

function formatKnownGitProbeSuccess(commandText: string, stdout?: string, stderr?: string): string | null {
  if (!commandText.startsWith('git ')) return null

  const output = formatCompactCommandOutput(stdout, stderr)
  if (commandText.includes(' show-ref --verify --quiet refs/')) {
    return output || 'ref found'
  }

  if (commandText.includes(' symbolic-ref --quiet --short refs/remotes/origin/HEAD')) {
    return output || 'origin/HEAD resolved'
  }

  if (commandText.includes(' diff --cached --quiet')) {
    return output || 'no staged changes'
  }

  if (commandText.includes(' rev-parse --abbrev-ref HEAD')) {
    return output || 'branch resolved'
  }

  return null
}

function formatKnownGitProbeFailure(commandText: string, error: string): string | null {
  if (!commandText.startsWith('git ')) return null
  if (!isLikelyBenignGitProbeFailure(error)) return null

  if (commandText.includes(' symbolic-ref --quiet --short refs/remotes/origin/HEAD')) {
    return 'origin/HEAD not set'
  }

  if (commandText.includes(' diff --cached --quiet')) {
    return 'staged changes present'
  }

  if (commandText.includes(' show-ref --verify --quiet refs/')) {
    return 'ref not found'
  }

  return null
}

function formatKnownSilentSuccess(bin: string, args: string[]): string | null {
  if (bin === 'git') return formatKnownSilentGitSuccess(args)
  if (bin === 'gh') return formatKnownSilentGhSuccess(args)
  return null
}

function formatKnownSilentGhSuccess(args: string[]): string | null {
  if (args[0] === 'pr' && args[1] === 'ready') return 'pull request marked ready'
  if (args[0] === 'api') return 'GitHub API request completed'
  return null
}

function formatKnownSilentGitSuccess(args: string[]): string | null {
  const command = getGitSubcommand(args)
  if (!command) return null

  switch (command.name) {
    case 'add':
      return 'files staged'
    case 'branch':
      if (args.includes('--show-current')) return 'branch not attached'
      if (args.includes('-D') || args.includes('-d') || args.includes('--delete')) return 'branch removed'
      return 'branch updated'
    case 'checkout':
      return 'checkout completed'
    case 'clean':
      return 'no files removed'
    case 'fetch':
      return 'fetch completed'
    case 'merge':
      return 'merge completed'
    case 'push':
      return 'push completed'
    case 'reset':
      return 'reset completed'
    case 'status':
      return args.includes('--porcelain') || args.some(arg => arg.startsWith('--porcelain='))
        ? 'worktree clean'
        : null
    case 'worktree': {
      const action = args[command.index + 1]
      if (action === 'add') return 'worktree added'
      if (action === 'remove') return 'worktree removed'
      if (action === 'prune') return 'worktree metadata pruned'
      return null
    }
    case 'ls-files':
      return args.includes('--others') ? 'no untracked files' : 'no files matched'
    case 'diff':
      return args.includes('--name-only') || args.includes('--name-status') || args.includes('--stat')
        ? 'no diff'
        : null
    default:
      return null
  }
}

function getGitSubcommand(args: string[]): { name: string; index: number } | null {
  for (let index = 0; index < args.length; index++) {
    const arg = args[index]
    if (!arg) continue

    if (
      arg === '-C'
      || arg === '-c'
      || arg === '--git-dir'
      || arg === '--work-tree'
      || arg === '--namespace'
    ) {
      index += 1
      continue
    }

    if (
      arg.startsWith('-C')
      || arg.startsWith('-c')
      || arg.startsWith('--git-dir=')
      || arg.startsWith('--work-tree=')
      || arg.startsWith('--namespace=')
    ) {
      continue
    }

    if (arg.startsWith('-')) continue
    return { name: arg, index }
  }

  return null
}

function truncateOutput(text: string, maxLen = LOG_TRUNCATION_LENGTH): string {
  if (text.length <= maxLen) return text
  return `${text.slice(0, maxLen)}… (truncated)`
}
