export const BEAD_RETRY_BUDGET_EXHAUSTED = 'BEAD_RETRY_BUDGET_EXHAUSTED' as const
export const BEAD_AGENT_RESPONSE_INVALID = 'BEAD_AGENT_RESPONSE_INVALID' as const
export const BEAD_ITERATION_TIMEOUT = 'BEAD_ITERATION_TIMEOUT' as const
export const BEAD_FINALIZATION_FAILED = 'BEAD_FINALIZATION_FAILED' as const
export const FINAL_TEST_FAILED = 'FINAL_TEST_FAILED' as const
export const OPENCODE_OUTPUT_TRUNCATED = 'OPENCODE_OUTPUT_TRUNCATED' as const
export const OPENCODE_PROVIDER_AUTH_FAILED = 'OPENCODE_PROVIDER_AUTH_FAILED' as const
export const OPENCODE_PROVIDER_ERROR = 'OPENCODE_PROVIDER_ERROR' as const
