/**
 * Renders the descriptor each managed package channel publishes, and reads back
 * the three facts that matter from one somebody else may have written.
 *
 * All three channels install the same bundle, and all three descriptors are
 * therefore the same four values in three syntaxes: version, URL, sha256, and
 * the name of the executable to shim. Rendering them from one place means a
 * release cannot publish a formula and a manifest that disagree about which
 * bytes this version is.
 *
 * Pure, and golden-file tested, because a mistake here is not caught by
 * anything downstream: a formula with a wrong sha256 installs green in CI
 * against the file CI just built and fails for every user.
 */

export type Channel = 'homebrew' | 'scoop' | 'chocolatey'

export interface ChannelInputs {
  version: string
  /** Where the bundle is fetched from. A release asset URL, or a local one in tests. */
  url: string
  sha256: string
}

/**
 * Under 80 characters, not starting with an article or the formula name, as
 * `brew audit --strict` requires. Deliberately not `package.json`'s
 * description, which is three times too long and would fail that check.
 */
export const SHORT_DESCRIPTION = 'Local AI coding orchestration with council planning and human-gated PRs'

export const HOMEPAGE = 'https://www.looptroop.ovh/'
export const REPOSITORY = 'https://github.com/looptroop-ai/LoopTroop'
export const LICENSE = 'MIT'

/** Written at the package root so LoopTroop can name the upgrade command. */
export const CHANNEL_MARKER = '.install-channel'

/** The top-level directory inside the bundle archive. */
export const BUNDLE_ROOT = 'looptroop'

function assertInputs({ version, url, sha256 }: ChannelInputs): void {
  if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) throw new Error(`Not a version: ${version}`)
  if (!/^[0-9a-f]{64}$/.test(sha256)) throw new Error(`Not a sha256: ${sha256}`)
  if (url === '') throw new Error('The bundle URL is empty.')
}

/**
 * The Homebrew formula.
 *
 * Two decisions worth naming. `node@24` is keg-only, so its `node` is not on
 * anybody's PATH; the launcher's shebang is `#!/usr/bin/env node`, so a plain
 * symlink into `bin` would install green and then die with `env: node: No such
 * file`. `write_env_script` puts the keg's bin on PATH for this command only.
 *
 * And `uses_from_macos "git"` rather than `depends_on "git"`: macOS provides
 * git, and `brew audit` rejects depending on what the OS already has — but
 * Linuxbrew does not, and `doctor` treats git as required, so it cannot simply
 * be dropped either.
 */
export function renderHomebrewFormula(inputs: ChannelInputs): string {
  assertInputs(inputs)

  return `# Generated by scripts/package-manifests.ts. Do not edit by hand.
class Looptroop < Formula
  desc "${SHORT_DESCRIPTION}"
  homepage "${HOMEPAGE}"
  url "${inputs.url}"
  sha256 "${inputs.sha256}"
  license "${LICENSE}"
  version "${inputs.version}"

  depends_on "gh"
  depends_on "node@24"
  uses_from_macos "git"

  def install
    libexec.install Dir["*"]
    (libexec/"${CHANNEL_MARKER}").write "homebrew"
    (bin/"looptroop").write_env_script libexec/"bin/looptroop",
                                       PATH: "#{Formula["node@24"].opt_bin}:$PATH"
  end

  def caveats
    <<~EOS
      LoopTroop drives OpenCode, which it does not install. Run:
        looptroop doctor
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/looptroop --version")
  end

  livecheck do
    url :stable
    strategy :github_latest
  end
end
`
}

/**
 * The Scoop manifest.
 *
 * `bin` points at the `.cmd` wrapper: Scoop's shim runs the target directly and
 * a `#!` script is not executable on Windows, so shimming `bin/looptroop` would
 * produce a command that exists and cannot run.
 *
 * `checkver` without `autoupdate` on purpose. Autoupdate would make Excavator a
 * second writer of this file, computing its own hash from whatever it found —
 * and the release is supposed to be the only thing that says what a version's
 * bytes are.
 */
export function renderScoopManifest(inputs: ChannelInputs): string {
  assertInputs(inputs)

  const manifest = {
    version: inputs.version,
    description: SHORT_DESCRIPTION,
    homepage: HOMEPAGE,
    license: LICENSE,
    url: inputs.url,
    hash: inputs.sha256,
    extract_dir: BUNDLE_ROOT,
    // `git` because doctor treats it as required, and Windows does not ship it.
    depends: ['nodejs-lts', 'git'],
    bin: [['bin\\looptroop.cmd', 'looptroop']],
    post_install: [
      `Set-Content -LiteralPath "$dir\\${CHANNEL_MARKER}" -Value 'scoop' -NoNewline`,
    ],
    notes: [
      'LoopTroop drives OpenCode, which it does not install. Run: looptroop doctor',
    ],
    checkver: { github: REPOSITORY },
  }

  return `${JSON.stringify(manifest, null, 4)}\n`
}

/**
 * The Chocolatey package specification.
 *
 * The bundle is embedded in the package rather than downloaded at install time,
 * so `LICENSE.txt` and `VERIFICATION.txt` are mandatory: Chocolatey's moderators
 * reject a package carrying binaries whose provenance is not stated.
 */
export function renderNuspec(inputs: ChannelInputs): string {
  assertInputs(inputs)

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/package-manifests.ts. Do not edit by hand. -->
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <id>looptroop</id>
    <version>${inputs.version}</version>
    <packageSourceUrl>${REPOSITORY}</packageSourceUrl>
    <owners>LoopTroop AI</owners>
    <title>LoopTroop</title>
    <authors>LoopTroop AI</authors>
    <projectUrl>${HOMEPAGE}</projectUrl>
    <licenseUrl>${REPOSITORY}/blob/v${inputs.version}/LICENSE</licenseUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <projectSourceUrl>${REPOSITORY}</projectSourceUrl>
    <docsUrl>${HOMEPAGE}docs</docsUrl>
    <bugTrackerUrl>${REPOSITORY}/issues</bugTrackerUrl>
    <tags>looptroop ai coding-agent orchestration opencode cli</tags>
    <summary>${SHORT_DESCRIPTION}</summary>
    <description>${SHORT_DESCRIPTION}. LoopTroop runs as a local background service and drives OpenCode in isolated git worktrees, with human approval gates before anything is delivered.</description>
    <dependencies>
      <dependency id="nodejs-lts" version="24.15.0" />
      <dependency id="git" />
    </dependencies>
  </metadata>
  <files>
    <file src="tools\\**" target="tools" />
  </files>
</package>
`
}

export function renderDescriptor(channel: Channel, inputs: ChannelInputs): string {
  switch (channel) {
    case 'homebrew': return renderHomebrewFormula(inputs)
    case 'scoop': return renderScoopManifest(inputs)
    case 'chocolatey': return renderNuspec(inputs)
  }
}

/** Where each channel's descriptor lives in its repository. */
export const DESCRIPTOR_PATH: Record<Channel, string> = {
  homebrew: 'Formula/looptroop.rb',
  scoop: 'bucket/looptroop.json',
  chocolatey: 'looptroop.nuspec',
}

export interface ParsedDescriptor {
  version: string | null
  url: string | null
  sha256: string | null
}

/**
 * The three facts, read back out of a descriptor this did not necessarily write.
 *
 * Comparing rendered text against remote text would call a comment change a
 * conflict and block a release over nothing; these are the fields that decide
 * what a user actually installs, so these are what get compared.
 *
 * Anything unreadable comes back as `null` rather than throwing, because "the
 * remote file is not a descriptor we understand" is a state the caller has to
 * handle deliberately, not an exception in the middle of a release.
 */
export function parseDescriptor(channel: Channel, text: string): ParsedDescriptor {
  if (channel === 'scoop') {
    try {
      const parsed = JSON.parse(text) as { version?: unknown, url?: unknown, hash?: unknown }
      return {
        version: typeof parsed.version === 'string' ? parsed.version : null,
        url: typeof parsed.url === 'string' ? parsed.url : null,
        sha256: typeof parsed.hash === 'string' ? parsed.hash.replace(/^sha256:/, '') : null,
      }
    } catch {
      return { version: null, url: null, sha256: null }
    }
  }

  if (channel === 'homebrew') {
    return {
      version: /^\s*version\s+"([^"]+)"/m.exec(text)?.[1] ?? null,
      url: /^\s*url\s+"([^"]+)"/m.exec(text)?.[1] ?? null,
      sha256: /^\s*sha256\s+"([^"]+)"/m.exec(text)?.[1] ?? null,
    }
  }

  // The nuspec carries the version; the URL and checksum live in the install
  // script beside it, and a repair pushes both, so both files are handed here
  // concatenated rather than parsed separately.
  return {
    version: /<version>([^<]+)<\/version>/.exec(text)?.[1] ?? null,
    url: /url(?:64)?\s*=\s*['"]([^'"]+)['"]/i.exec(text)?.[1] ?? null,
    sha256: /checksum(?:64)?\s*=\s*['"]([0-9a-fA-F]{64})['"]/i.exec(text)?.[1]?.toLowerCase() ?? null,
  }
}
