# Generated by scripts/package-manifests.ts. Do not edit by hand.
class Looptroop < Formula
  desc "Local AI coding orchestration with council planning and human-gated PRs"
  homepage "https://www.looptroop.ovh/"
  url "https://github.com/looptroop-ai/LoopTroop/releases/download/v9.9.9/looptroop-9.9.9-bundle.tar.gz"
  sha256 "3c5fe4640000000000000000000000000000000000000000000000000000abcd"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on "gh"
  depends_on "node@24"
  uses_from_macos "git"

  def install
    libexec.install Dir["*"]
    (libexec/".install-channel").write "homebrew"
    (bin/"looptroop").write_env_script libexec/"bin/looptroop",
                                       PATH: "#{formula_opt_bin("node@24")}:$PATH"
  end

  def caveats
    <<~EOS
      LoopTroop drives OpenCode, which it does not install. Run:
        looptroop doctor
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/looptroop --version")
  end
end
